agent/agent-core/src/main/java/org/bithon/agent/core/plugin/PluginConfigurationManager.java, agent/agent-core/src/main/java/org/bithon/agent/core/plugin/PluginInterceptorInstaller.java, doc/configuration.md
=> Fix plugin configuration prefix

server/collector/src/main/java/org/bithon/server/tracing/storage/ITraceWriter.java, server/collector/src/main/java/org/bithon/server/tracing/storage/TraceConfig.java, server/collector/src/main/java/org/bithon/server/tracing/storage/jdbc/TraceJdbcStorage.java, server/collector/src/main/java/org/bithon/server/tracing/storage/ttl/TraceTTLManager.java, server/server-starter/src/main/resources/application-collector.yml
=> add TTL to trace

server/web-app/src/main/java/org/bithon/server/webapp/ui/AppController.java, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/sidebar/component.js, server/web-app/src/main/resources/templates/app/app-layout.html, server/web-app/src/main/resources/templates/app/topo.html, server/web-app/src/main/resources/templates/app/trace.html
=> Remember instance selection state

server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/ClickHouseSqlExpressionFormatter.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/ISqlExpressionFormatter.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java
Introduced by previous PR #223
=> Fix SQL on H2

server/collector/src/main/java/org/bithon/server/metric/api/CardinalityAggregator.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/QuerableAggregatorSqlVisitor.java
=> Quote alias so that the name won't be changed to ALL uppercase under H2

agent/agent-core/src/main/java/org/bithon/agent/core/tracing/id/ISpanIdGenerator.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/id/impl/DefaultSpanIdGenerator.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java
1. Fix the padding of span id
2. Fix the display order of spans
=> Fix span related bugs

agent/agent-core/src/main/java/org/bithon/agent/core/aop/descriptor/BithonClassDescriptor.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/descriptor/MatcherUtils.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/descriptor/MethodPointCutDescriptorBuilder.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/Tracer.java, agent/agent-plugins/spring-webflux/README.md, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/SpringWebFluxPlugin.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/context/HttpClientContext.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/context/HttpServerContext.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientChannelInitializer$OnChannelInit.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientFinalizer$ResponseConnection.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientFinalizer$Send.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientOperations$Ctor.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpServerChannelInitializer$OnChannelInit.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpServerOperations$Ctor.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/metric/HttpBodySizeCollector.java, server/collector/src/main/java/org/bithon/server/metric/handler/HttpOutgoingMetricMessageHandler.java
metrics out of trace
trace
io metrics
=> Trace and HttpClient metric support on weblufx

agent/agent-core/src/main/java/org/bithon/agent/core/config/Configuration.java, agent/agent-core/src/main/java/org/bithon/agent/core/metric/domain/web/HttpIncomingFilter.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/config/TraceConfig.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/ITraceSpan.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/ContextHandlerDoHandle.java, agent/agent-plugins/webserver-tomcat/src/main/java/org/bithon/agent/plugin/tomcat/interceptor/StandardHostValveInvoke.java
=> Support to record specified HTTP header to trace log

pom.xml, server/collector/pom.xml, server/server-starter/pom.xml, server/sink/pom.xml, server/storage-jdbc/pom.xml, server/web-app/pom.xml, server/web-service/pom.xml
To eliminate potential vulnerabilities.
- Spring Cloud ---> SR12
- Spring Boot ---> 2.3.12
=> Update Spring Cloud/Boot

docker/Dockerfile-server, docker/README.md, docker/startup.sh, server/web-app/src/main/java/org/bithon/server/webapp/services/ServiceDiscovery.java
1. Support external jvm configuration
2. Fix incorrect apiHost detection
=> Docker improvement

agent/agent-core/src/main/java/org/bithon/agent/core/context/AgentContext.java, agent/agent-core/src/main/java/org/bithon/agent/core/context/AppInstance.java, agent/agent-core/src/main/java/org/bithon/agent/core/metric/domain/web/HttpIncomingFilter.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/propagation/extractor/ChainedTraceContextExtractor.java, agent/agent-plugins/guice/src/main/java/org/bithon/agent/plugin/guice/GuicePlugin.java, agent/agent-plugins/spring-bean/src/main/java/org/bithon/agent/plugin/spring/bean/SpringBeanPlugin.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/SpringWebFluxPlugin.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/ServiceMessageChannelHandler.java
Fixes some problems in #250 
1. fixes problem 1 in #250 to support bithon.application.instance to resolve instance conflicts in docker running on different host
2. fixes problem 4 in #250 to resolve stack trace printing
3. fixes problem 5 in #250 to filter .map by default
4. fixes problem 6 in #250 to resolve concurrent exception raised
5. also removed some debug indicator from some plugins
=> Fix bugs in agent

agent/agent-plugins/jvm/src/main/java/org/bithon/agent/plugin/jvm/JvmMetricCollector.java, docker/Dockerfile-server, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcWriter.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricTable.java, server/web-app/src/main/resources/static/js/page/event/page.js, server/web-app/src/main/resources/static/js/page/trace/page.js
1. Modify docker file to include shaded processing
2. improve indexes on dimensions
3. Fix webui refresh interval
=> Bugs fixes

server/sink/src/main/java/org/bithon/server/common/handler/AbstractThreadPoolMessageHandler.java, server/sink/src/main/java/org/bithon/server/tracing/sink/TraceMessageHandler.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java
Simply improvement, 3x performance gain.
=> Support batch writing on trace data

agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/ApacheHttpClientPlugin.java, agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/interceptor/HttpRequestExecutor$Execute.java, agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/metrics/DefaultRequestDirector$Execute.java, agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/metrics/DefaultRequestDirector$ReleaseConnection.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/JdkHttpClientPlugin.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$New.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$ParseHttp.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$WriteRequest.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpsClient$New.java, agent/agent-plugins/httpclient-okhttp3/src/main/java/org/bithon/agent/plugin/httpclient/okhttp3/OkHttp3HttpClientPlugin.java, agent/agent-plugins/httpclient-okhttp3/src/main/java/org/bithon/agent/plugin/httpclient/okhttp3/RealCall$GetResponseWithInterceptorChain.java, agent/agent-plugins/httpclient-okhttp32/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/OkHttp32HttpClientPlugin.java, agent/agent-plugins/httpclient-okhttp32/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/RealCall$GetResponseWithInterceptorChain.java
=> Comply with interceptor naming specification in http client modules

server/collector/src/main/java/org/bithon/server/collector/source/http/TraceHttpCollector.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java
Use real batch api to improve perf and reduce memory
=> Improve batch performance

agent/agent-sentinel/src/main/java/org/bithon/agent/sentinel/flow/IFlowRuleManager.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/cmd/IJvmCommand.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/event/IEventCollector.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/metrics/IMetricCollector.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/tracing/ITraceCollector.java, component/component-brpc/src/main/java/org/bithon/component/brpc/BrpcMethod.java, component/component-brpc/src/main/java/org/bithon/component/brpc/BrpcService.java, component/component-brpc/src/main/java/org/bithon/component/brpc/ServiceConfiguration.java, component/component-brpc/src/main/java/org/bithon/component/brpc/ServiceRegistry.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/ServerChannel.java, component/component-brpc/src/main/java/org/bithon/component/brpc/exception/DuplicateServiceException.java, component/component-brpc/src/main/java/org/bithon/component/brpc/exception/ServiceRegistrationException.java, component/component-brpc/src/test/java/org/bithon/component/brpc/RpcTest.java, component/component-brpc/src/test/java/org/bithon/component/brpc/example/IExampleService.java, server/sink/src/main/resources/schema/jvm-gc-metrics.json
=> Add BrpcService annotation

server/web-app/src/main/resources/static/js/component/time-interval/component.js, server/web-app/src/main/resources/static/js/page/event/page.js, server/web-app/src/main/resources/static/js/page/trace/page.js, server/web-app/src/main/resources/templates/app/app-layout.html
A necessary improvement on the UI
=> Set default interval on event page to 'all'

agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/SpringWebFluxPlugin.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/AroundGatewayFilter$Filter.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/BeforeGatewayFilter$Filter.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ChannelOperations$OnInboundComplete.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ChannelOperations$onInboundComplete.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientChannelInitializer$OnChannelInit.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpServerChannelInitializer$OnChannelInit.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpServerOperations$Ctor.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/metric/HttpBodySizeCollector.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/metric/HttpIOMetrics.java
A lost commit on previous PR #279
=> Fix Gateway filter

server/sink/src/main/java/org/bithon/server/common/matcher/IMatcherVisitor.java, server/sink/src/main/java/org/bithon/server/common/matcher/IStringMatcher.java, server/sink/src/main/java/org/bithon/server/common/matcher/NotEqualMatcher.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/web-app/src/main/resources/static/js/chart-component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/table/component.js, server/web-service/src/main/java/org/bithon/server/web/service/api/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/api/GroupByQueryRequest.java
To provide a way to dive into the details of metrics.
Also this provides a way to provide 'groupBy' semantics described in #47
=> Add detail view to metric chart

server/web-app/src/main/resources/templates/app/app-layout.html
=> Fix a lost commit that causes metric chart broken

agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/interceptor/HttpRequestExecutor$Execute.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceMapBuilder.java
=> Fix the URL in apache http client

server/web-app/src/main/resources/dashboard/http-incoming-metrics.json, server/web-app/src/main/resources/dashboard/http-outgoing-metrics.json
=> Add detail view for http error metrics

server/sink/src/main/resources/schema/jvm-gc-metrics.json, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/web-app/src/main/resources/dashboard/jvm-metrics.json, server/web-app/src/main/resources/static/js/chart-component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-service/src/main/java/org/bithon/server/web/service/api/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/api/DataSourceService.java, server/web-service/src/main/java/org/bithon/server/web/service/api/TimeSeriesQueryRequest.java
Fixes #47 
```json
{
"dataSource": "jvm-gc-metrics",
"title": "Old GC",
"width": 4,
"dimensions": {
"generation": {
"dimension": "generation",
"matcher": {
"type": "equal",
"pattern": "old"
}
}
},
"metrics": [ {
"name": "avgGcTime",
"yAxis": 1
}
],
"groupBy": [
"gcName"
]
}
```
=> Add groupby sematic support

server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java
Caused by #293 , lack of test on H2.
=> Fix group bug in H2 storage

server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/table/component.js, server/web-app/src/main/resources/static/js/utils/number.js, server/web-app/src/main/resources/static/js/utils/time.js
The least work to make it work.
lookup configuration in chart:
```json
"details": {
"groupBy": [
"cluster",
"user",
"queryType",
"exceptionCode"
],
"metrics": [
"qps",
"requestTotal"
],
"lookup": {
"exceptionCode": {
"0": "OK",
"1": "UNSUPPORTED_METHOD",
"2": "UNSUPPORTED_PARAMETER"
}
}
}
```
=> Support lookup in detail view

server/web-app/src/main/resources/static/js/component/tree-table/component.js, server/web-app/src/main/resources/templates/trace/detail.html
A must-do work at the webapp side to make current work more efficient by improving the rendering speed at least 100X
=> Improve detail view performance

server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java, server/web-app/src/main/java/org/bithon/server/webapp/ui/TraceController.java, server/web-app/src/main/resources/static/js/page/trace/page.js, server/web-app/src/main/resources/static/js/utils/location.js, server/web-app/src/main/resources/templates/trace/detail.html
Some work to avoid a bug that open a detail on the list page does not show any result because of global search bar default interval on the detail page. So,
1. Remove the global search bar
2. extract interval from the URL
3. passing interval on list page to detail page
=> Improve trace detail page

server/web-app/src/main/resources/static/js/component/searchbar/component.js, server/web-app/src/main/resources/static/js/component/tree-table/component.js, server/web-app/src/main/resources/templates/trace/detail.html
=> Fix a search bug

server/collector/src/main/java/org/bithon/server/collector/source/brpc/BrpcMetricCollector.java
=> Fix wrong order of data

agent/agent-plugins/httpclient-netty3/src/main/java/org/bithon/agent/plugin/httpclient/netty3/Channels$Write.java, server/sink/src/main/java/org/bithon/server/tracing/TraceDataSourceSchema.java, server/sink/src/main/java/org/bithon/server/tracing/sink/TraceSpan.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java, server/web-app/src/main/resources/static/js/page/trace/page.js
A follow up of #322 , use summary table to search the trace list and distribution
=> Use summary table

server/sink/src/main/java/org/bithon/server/tracing/sanitization/UrlSanitizer.java, server/sink/src/main/java/org/bithon/server/tracing/sink/TraceSpan.java
=> Fix a bug caused by the tag name standardisation

.github/workflows/build11.yml, .github/workflows/build17.yml, .github/workflows/build8.yml, .github/workflows/push-docker-agent.yml, README.md, component/agent-rpc-brpc/pom.xml, component/component-brpc/pom.xml, component/component-commons/pom.xml, component/pom.xml, docker/Dockerfile-agent, docker/Dockerfile-server, docker/startup.sh, pom.xml, server/sink/src/main/java/org/bithon/server/metric/DataSourceSchemaManager.java, server/web-service/src/main/java/org/bithon/server/web/service/api/DataSourceApi.java
1. restore Docker-agent in case some applications want to use the agent images
2. automatically push the agent image to the docker hub automatically by using GitHub Actions
3. Support passing application arguments via environment variable `APP_OPTS`
=> Docker improvements

agent/agent-core/src/main/java/org/bithon/agent/core/aop/descriptor/Descriptors.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/descriptor/InterceptorDescriptor.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/descriptor/InterceptorDescriptorBuilder.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/JdkHttpClientPlugin.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/ThreadPlugin.java
No need to treat any class in bootstrap class loader in a special way
=> Remove bootstrap related code

agent/agent-plugins/pom.xml, agent/agent-plugins/spring-bean/src/main/java/org/bithon/agent/plugin/spring/bean/installer/BeanMethodAopInstallerHelper.java, agent/agent-plugins/spring-bean/src/main/java/org/bithon/agent/plugin/spring/bean/interceptor/BeanMethod$Invoke.java, agent/agent-plugins/spring-mvc/src/main/java/org/bithon/agent/plugin/spring/mvc/SpringMvcPlugin.java, agent/agent-plugins/spring-mvc/src/main/java/org/bithon/agent/plugin/spring/mvc/SynchronousMethodHandler$Invoke.java, agent/agent-plugins/spring-mvc/src/main/java/org/bithon/agent/plugin/spring/mvc/SynchronousMethodHandlerFactory$Create.java, agent/agent-plugins/spring-scheduling/pom.xml, agent/agent-plugins/spring-scheduling/src/main/java/org/bithon/agent/plugin/spring/scheduling/ScheduledMethodRunnable$Run.java, agent/agent-plugins/spring-scheduling/src/main/java/org/bithon/agent/plugin/spring/scheduling/SpringSchedulingPlugin.java
=> Improve Spring support

server/sink/src/main/java/org/bithon/server/metric/storage/ListQuery.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/table/component.js, server/web-service/src/main/java/org/bithon/server/web/service/api/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/api/ListQueryRequest.java
Caused by the OrderBy support in #350
=> Fix list query bug for front end table component

server/web-app/src/main/resources/static/js/component/dashboard/component.js
=> Show year/month/date for the chart tooltip

doc/configuration/configuration-storage.md, server/server-starter/src/main/resources/application-storage-hybrid.yml, server/server-starter/src/main/resources/application-storage-jdbc.yml, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/ClickHouseStorageAutoConfiguration.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/EventStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/MetadataStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/MetricStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/SchemaStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/SettingStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/TraceStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/JdbcStorageAutoConfiguration.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/event/EventJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/meta/MetadataJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/meta/SchemaJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/setting/SettingJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java
=> Allow using multiple storage systems simultaneously

server/web-app/src/main/resources/static/js/component/app-selector/component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/sidebar/component.js, server/web-app/src/main/resources/static/js/page/event/page.js, server/web-app/src/main/resources/static/js/page/trace/page.js, server/web-app/src/main/resources/templates/app/app-layout.html, server/web-app/src/main/resources/templates/app/topo.html, server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/GetTraceDistributionRequest.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/GetTraceListRequest.java
=> No page reload after application is switched

server/web-app/src/main/resources/static/js/component/app-selector/component.js
=> Cache the filter results and support search

server/web-app/src/main/resources/templates/_common/layout.html, server/web-app/src/main/resources/templates/app/app-layout.html
=> Fix minor UI problems

agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/interceptor/HttpRequestExecutor$Execute.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java
=> Fix two plugin prolems

agent/agent-bootstrap/src/main/java/org/bithon/agent/bootstrap/aop/advice/MethodDecoratorAdvice.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/ITraceSpan.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/TraceSpan.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/AroundGatewayFilter$Filter.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/BeforeGatewayFilter$Filter.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/Flux$Timeout.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, dev/spotbugs-exclude.xml, pom.xml
=> Fix wrong span level when exception thrown during routing

server/web-app/src/main/resources/static/js/component/app-selector/component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/utils/number.js
Some improvements at web side with least work to make our work more smooth.
=> Some improvements at web side

server/web-app/src/main/java/org/bithon/server/webapp/ui/DashboardController.java, server/web-app/src/main/resources/static/js/chart-component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/time-interval/component.js, server/web-app/src/main/resources/static/js/component/trace/trace-list-component.js
including some necessary bug fixes and some improvements
=> Web improvement

agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/ITraceSpan.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/NullTraceSpan.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/PropagationTraceSpan.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/TraceSpan.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/ThreadPlugin.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/threadpool/ThreadPoolExecutor$AfterExecute.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/threadpool/ThreadPoolExecutor$Execute.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/threadpool/ThreadPoolExecutor$Shutdown.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/threadpool/TracedRunnable.java
=> Add tracing support to thread pool

shaded/shaded-protobuf/pom.xml
Signed-off-by: Frank Chen <frank.chen021@outlook.com>
=> bump protobuf to support Mac M1

component/component-commons/src/main/java/org/bithon/component/commons/time/DateTime.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/DataCleaner.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/EventStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/MetricStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/TraceStorage.java
Original ALTER TABLE DELETE is a very heavy operation
=> Use drop partition to expire data in ClickHouse

component/component-commons/src/main/java/org/bithon/component/commons/utils/StringUtils.java, server/sink/src/main/java/org/bithon/server/kafka/KafkaConsumerStarter.java, server/sink/src/main/java/org/bithon/server/sink/metrics/LocalMetricSink.java, server/sink/src/main/java/org/bithon/server/sink/metrics/LocalSchemaMetricSink.java, server/sink/src/main/java/org/bithon/server/sink/metrics/MetricMessageHandler.java, server/sink/src/main/java/org/bithon/server/sink/metrics/MetricMessageHandlers.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/meta/SchemaJdbcStorage.java, server/storage/src/main/java/org/bithon/server/storage/configurer/StorageAutoConfiguration.java, server/storage/src/main/java/org/bithon/server/storage/datasource/DataSourceSchemaManager.java, server/storage/src/main/java/org/bithon/server/storage/meta/ISchemaStorage.java
A necessary refactoring to generalize metric handling
=> Extract message handlers out of LocalMetricSink

agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/TraceContextListener.java, agent/agent-plugins/logging-log4j2/src/main/java/org/bithon/agent/plugin/log4j2/interceptor/PatternParserCtor.java, agent/agent-plugins/logging-logback/src/main/java/org/bithon/agent/plugin/logback/interceptor/PatternLayoutCtor.java
=> Fix concurrency problem in agent

server/sink/src/main/java/org/bithon/server/sink/SinkAutoConfiguration.java, server/sink/src/main/java/org/bithon/server/sink/metrics/topo/HttpOutgoingMetricTopoTransformer.java, server/sink/src/main/java/org/bithon/server/sink/metrics/transformer/ExtractHost.java, server/sink/src/main/java/org/bithon/server/sink/metrics/transformer/ExtractPath.java, server/sink/src/main/resources/schema/http-outgoing-metrics.json
=> Fix a bug that http-outgoing metrics are not recorded

agent/agent-core/src/main/java/org/bithon/agent/core/dispatcher/Dispatchers.java
=> Fix concurrency exception

component/component-brpc/src/main/java/org/bithon/component/brpc/channel/ClientChannel.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/ServiceMessageChannelHandler.java, component/component-brpc/src/main/java/org/bithon/component/brpc/exception/ChannelException.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/ClientInvocationManager.java
=> Improve fault tolerance at channel layer

agent/agent-core/src/main/java/org/bithon/agent/core/tracing/Tracer.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/config/TraceConfig.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/sampler/SamplerFactory.java, agent/agent-distribution/resources/agent.yml, agent/agent-plugins/apache-druid/src/main/java/org/bithon/agent/plugin/apache/druid/ApacheDruidPlugin.java, agent/agent-plugins/bithon-brpc/src/main/java/org/bithon/agent/plugin/bithon/brpc/interceptor/BrpcMethodInterceptor.java, agent/agent-plugins/guice/src/main/java/org/bithon/agent/plugin/guice/GuicePlugin.java, agent/agent-plugins/quartz2/src/main/java/org/bithon/agent/plugin/quartz2/JobRunShell$Run.java, agent/agent-plugins/spring-bean/src/main/java/org/bithon/agent/plugin/spring/bean/SpringBeanPlugin.java, agent/agent-plugins/spring-scheduling/src/main/java/org/bithon/agent/plugin/spring/scheduling/ScheduledMethodRunnable$Run.java, doc/configuration/configuration-agent.md
Before
```
bithon.tracing.samplingRate
```
After
```
bithon.tracing.default.samplingRate
```
=> Separate sampling configuration for different entries

server/sink/src/main/java/org/bithon/server/sink/tracing/metrics/MetricOverSpanInputSource.java
Current storages for metrics over tracing are initialized when there're matched spans. But at front end, users may open dashboard before these storages are initialized. This PR makes sure the storages are created once their schemas are loaded
=> Initialize metric storage first

server/server-commons/src/main/java/org/bithon/server/commons/time/TimeSpan.java, server/server-commons/src/test/java/org/bithon/server/commons/time/TimeSpanTest.java
Caused TTL expiration in wrong time
=> Fix bugs in timespan

.github/workflows/build11.yml, .github/workflows/build17.yml, .github/workflows/build8.yml, README.md, pom.xml
Original build command in GitHub action generates agent-distribution very strangely, containing some unexpected libs.
=> Fix generated agent-distribution by GitHub action

agent/agent-core/src/main/java/org/bithon/agent/core/metric/domain/http/HttpOutgoingMetricsRegistry.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/TraceContextHolder.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/JdkHttpClientPlugin.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$New.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$ParseHTTP.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$WriteRequests.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClientContext.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpsClient$New.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/NetworkClient$DoConnect.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/Socket$GetInputStream.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/Socket$GetOutputStream.java, server/web-app/src/main/resources/dashboard/http-outgoing-metrics.json
=> Support IO metrics of JDK HTTP client

server/sink/src/main/java/org/bithon/server/sink/common/handler/AbstractThreadPoolMessageHandler.java, server/sink/src/main/java/org/bithon/server/sink/metrics/MetricInputSource.java, server/sink/src/main/java/org/bithon/server/sink/metrics/MetricMessageHandlers.java, server/sink/src/main/java/org/bithon/server/sink/tracing/TraceMessageProcessChain.java, server/sink/src/main/java/org/bithon/server/sink/tracing/metrics/MetricOverSpanInputSource.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/TableCreator.java, server/storage/src/main/java/org/bithon/server/storage/meta/CachableMetadataStorage.java, server/web-app/src/main/java/org/bithon/server/webapp/ui/DashboardController.java, server/web-app/src/main/resources/dashboard/exception-metrics.json, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/table/component.js
1. Use inner class instead of lamda to improve the tracing logs
2. close message handler when input source is stopped
3. don't use message schema sinker in MetricOverSpanInputSource
4. improve error handling in dashboard api
5. support orderBy/lookup in list component
6. add cache to not found instance to improve performance. As can seen from the pic, queryCount drops to 2.8K to less than 400
=> Improve message sinker

shaded/shaded-jackson/pom.xml
=> Bump jackson to 2.13.4

agent/agent-core/src/main/java/org/bithon/agent/core/tracing/config/TraceConfig.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/HttpChannel$Handle.java, agent/agent-plugins/webserver-tomcat/src/main/java/org/bithon/agent/plugin/tomcat/interceptor/StandardHostValveInvoke.java, agent/agent-plugins/webserver-undertow/src/main/java/org/bithon/agent/plugin/undertow/interceptor/HttpServerExchangeDispatch.java, doc/configuration/configuration-agent.md
=> Support to inject trace id in the response

server/server-starter/src/main/java/org/bithon/server/starter/exception/GlobalExceptionHandler.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/web-app/src/main/resources/static/js/component/dashboard/component.js
to support the page can be integrated with other systems by passing filters without 'appName'
=> Remove filter restriction

shaded/shaded-bytebuddy/pom.xml
=> Bump bytebuddy from 1.11.18 to 1.12.18

agent/agent-bootstrap/pom.xml, agent/agent-bootstrap/src/main/java/org/bithon/agent/bootstrap/aop/advice/InterceptorResolver.java, agent/agent-bootstrap/src/main/java/org/bithon/agent/bootstrap/aop/advice/TargetMethodResolver.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/installer/DynamicInterceptorInstaller.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/installer/InterceptorInstaller.java
Not sure why CI for #470 didn't work
=> Adapt to latest bytebuddy

server/web-app/src/main/resources/dashboard/jvm-metrics.json, server/web-app/src/main/resources/static/js/chart-component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/templates/trace/detail.html
1. Use /api/datasource/timeseries/v2 to replace old interface at webapp side
2. Fixes #347 and #402
=> Use /api/datasource/timeseries/v2 to replace old interface at webapp side

hooks/pre-push.sh, pom.xml
=> Improve pre-push to check license on local

server/collector/src/main/java/org/bithon/server/collector/CollectorAutoConfiguration.java, server/server-starter/src/main/resources/application.yml, server/sink/src/main/java/org/bithon/server/sink/SinkAutoConfiguration.java, server/sink/src/main/java/org/bithon/server/sink/tracing/TraceConfig.java, server/sink/src/main/java/org/bithon/server/sink/tracing/TraceMessageProcessChain.java
The filter can be agent level or sink level. This adds the sink level.
=> Add span filter during sink

agent/agent-distribution/resources/agent.yml, agent/agent-plugins/jersey/pom.xml, agent/agent-plugins/jersey/src/main/java/org/bithon/agent/plugin/jersey/Jersey.java, agent/agent-plugins/jersey/src/main/java/org/bithon/agent/plugin/jersey/interceptor/ResourceJavaMethodDispatcher$Ctor.java, agent/agent-plugins/pom.xml, component/component-commons/src/main/java/org/bithon/component/commons/utils/ReflectionUtils.java
=> Add tracing support to JAX-RS implementation of Sun

agent/agent-plugins/kafka/src/main/java/org/bithon/agent/plugin/kafka/consumer/interceptor/ListenerConsumer$PollAndInvoke.java
Now the uri is as 'kafka://bootstrap-server?topic=xxx'
=> Improve Kafka uri

agent/agent-plugins/jvm/src/main/java/org/bithon/agent/plugin/jvm/cmd/JvmCommand.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/cmd/IJvmCommand.java, component/component-brpc/src/main/java/org/bithon/component/brpc/exception/ServiceInvocationException.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/ServiceInvocationRunnable.java, server/collector/src/main/java/org/bithon/server/collector/cmd/api/CommandApi.java
To support debug some problems
=> Support to dump loaded class list

agent/agent-core/src/main/java/org/bithon/agent/core/context/AgentContext.java, agent/agent-core/src/main/java/org/bithon/agent/core/context/AppInstance.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/Tracer.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/ITraceContext.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/PropagationTraceContext.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/TraceContext.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/propagation/DefaultPropagator.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/propagation/ITracePropagator.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/propagation/extractor/ChainedTraceContextExtractor.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/propagation/extractor/ITraceContextExtractor.java, agent/agent-core/src/main/java/org/bithon/agent/core/tracing/sampler/SamplerFactory.java, agent/agent-plugins/bithon-brpc/src/main/java/org/bithon/agent/plugin/bithon/brpc/interceptor/BrpcMethodInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/GrpcPlugin.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/AbstractGrpcStubInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/ClientCallInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/ManagedChannelImplBuilder$Build.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/server/interceptor/ServerBuilder$Build.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/server/interceptor/ServerCallInterceptor.java, agent/agent-plugins/quartz2/src/main/java/org/bithon/agent/plugin/quartz2/JobRunShell$Run.java, agent/agent-plugins/spring-bean/src/main/java/org/bithon/agent/plugin/spring/bean/installer/BeanMethodAopInstallerHelper.java, agent/agent-plugins/spring-bean/src/main/java/org/bithon/agent/plugin/spring/bean/interceptor/BeanMethod$Invoke.java, agent/agent-plugins/spring-scheduling/src/main/java/org/bithon/agent/plugin/spring/scheduling/ScheduledMethodRunnable$Run.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/HttpChannel$Handle.java, agent/agent-plugins/webserver-tomcat/src/main/java/org/bithon/agent/plugin/tomcat/interceptor/StandardHostValveInvoke.java, agent/agent-plugins/webserver-undertow/src/main/java/org/bithon/agent/plugin/undertow/interceptor/HttpServerExchangeDispatch.java
=> Support to grpc-server

agent/agent-core/src/main/java/org/bithon/agent/core/metric/domain/thread/ThreadPoolMetrics.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/interceptor/ForkJoinPool$Ctor.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/interceptor/ThreadPoolExecutor$Ctor.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/metrics/ForkJoinPoolMetrics.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/metrics/ThreadPoolExecutorMetrics.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/metrics/ThreadPoolMetricRegistry.java, server/sink/src/main/resources/schema/thread-pool-metrics.json, server/web-app/src/main/resources/dashboard/thread-pool-metrics.json
=> Remove poolId from thread pool metrics

agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$ParseHTTP.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpsClient$New.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/context/RequestContext.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/HttpChannel$Handle.java
=> Fix NPE in agent

agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/ListenerConsumer$PollAndInvoke.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/producer/interceptor/KafkaProducer$DoSend.java, server/web-app/src/main/resources/static/js/component/trace/trace-list-component.js, server/web-app/src/main/resources/templates/trace/detail.html, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceTopoBuilder.java
1. Add Kafka node to topo
2. improve the style of span logs, highlight the entry of span logs from one application
3. Add kafka bootsrap address to tracing log
=> Some small improvements on tracing

agent/agent-core/src/main/java/org/bithon/agent/core/aop/installer/BeanMethodAopInstaller.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/installer/DynamicInterceptorInstaller.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/AbstractAsyncStub$NewStub.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/AbstractBlockingStub$NewStub.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/AbstractFutureStub$NewStub.java, agent/agent-plugins/guice/src/main/java/org/bithon/agent/plugin/guice/installer/BeanMethodAopInstallerHelper.java, agent/agent-plugins/spring-bean/src/main/java/org/bithon/agent/plugin/spring/bean/installer/BeanMethodAopInstallerHelper.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/storage/MetadataStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/meta/MetadataJdbcStorage.java, server/storage/src/main/java/org/bithon/server/storage/meta/CacheableMetadataStorage.java, server/storage/src/main/java/org/bithon/server/storage/meta/IMetaStorage.java
New bug introduced by previouse PR #524
=> Avoid exception when saving to H2

server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/ServiceBroadcastInvoker.java, server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/inprocess/InProcessDiscoveryClient.java, server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/local/LocalDiscoveryClient.java
=> Support inprocess service discovery

agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/advice/AdviceAnnotation.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/installer/InstallerRecorder.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/installer/InterceptorInstaller.java, server/collector/src/main/java/org/bithon/server/collector/cmd/api/AgentCommandApi.java, server/service-discovery/declaration/src/main/java/org/bithon/server/discovery/declaration/cmd/IAgentCommandApi.java
=> Add interceptor name to InstrumentedMethodRecord

agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcAgentController.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcServer.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/Headers.java, component/component-brpc/src/test/java/org/bithon/component/brpc/BrpcRpcTest.java, server/collector/src/main/java/org/bithon/server/collector/cmd/api/AgentProxyApi.java, server/service-discovery/declaration/src/main/java/org/bithon/server/discovery/declaration/cmd/IAgentProxyApi.java
=> Add startAt

component/component-brpc/src/main/java/org/bithon/component/brpc/exception/CalleeSideException.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/InvocationManager.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/ServiceInvocationRunnable.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/out/ServiceResponseMessageOut.java, component/component-brpc/src/test/java/org/bithon/component/brpc/BrpcRpcTest.java, server/collector/src/main/java/org/bithon/server/collector/cmd/api/AgentProxyApi.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/AgentServiceProxyFactory.java
=> Ignore specific exception when proxing agent service

component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcClient.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcClientBuilder.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcServer.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/in/ServiceRequestMessageIn.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/out/ServiceRequestMessageOut.java, server/collector/src/main/java/org/bithon/server/collector/cmd/api/AgentProxyApi.java
Prevent from returning a lot of session objects where users send invalid service request message on the connection
=> Defer session create

README.md, agent/agent-controller/src/main/java/org/bithon/agent/controller/AgentControllerService.java, agent/agent-controller/src/main/java/org/bithon/agent/controller/IAgentController.java, agent/agent-controller/src/main/java/org/bithon/agent/controller/config/DynamicConfigurationManager.java, agent/agent-core/src/main/java/org/bithon/agent/configuration/Configuration.java, agent/agent-core/src/main/java/org/bithon/agent/starter/AgentStarter.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcAgentController.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcEventMessageChannel.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcMetricMessageChannel.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcTraceMessageChannel.java, agent/agent-distribution/resources/agent.yml, agent/agent-observability/src/main/java/org/bithon/agent/observability/context/AppConfiguration.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/context/AppInstance.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/Tracer.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/utils/NetworkUtils.java, docker/README.md, server/collector/src/main/java/org/bithon/server/collector/config/AgentConfigurationService.java, server/collector/src/main/java/org/bithon/server/collector/config/BrpcSettingFetcher.java, server/web-app/src/main/resources/dashboard/http-incoming-metrics.json, server/web-app/src/main/resources/dashboard/http-outgoing-metrics.json
Reverts FrankChen021/bithon#558
=> Revert "Simplifies configuration"

agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcAgentController.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcEventMessageChannel.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcMetricMessageChannel.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcTraceMessageChannel.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcClient.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcClientBuilder.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcServer.java, component/component-brpc/src/test/java/org/bithon/component/brpc/BrpcRpcTest.java, component/component-commons/src/main/java/org/bithon/component/commons/concurrency/NamedThreadFactory.java, server/collector/src/main/java/org/bithon/server/collector/source/brpc/BrpcCollectorStarter.java
To improve the efficiency of problem resolving if related error logs are printed
=> Add client/server id to brpc

server/storage/src/main/java/org/bithon/server/storage/datasource/DataSourceSchema.java, server/storage/src/main/java/org/bithon/server/storage/datasource/store/DataStoreSpec.java, server/web-app/src/main/resources/dashboard/exception-metrics.json, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/DataSourceApi.java
1. fix the displayed/selected range on the dashboard to ensure it's in the range of filter
2. mask password from returned schema
=> Log improvement

server/storage/src/main/java/org/bithon/server/storage/datasource/store/InternalDataSourceSpec.java
fixes a bug caused by previous PR
=> Fix serialization and deserialization

agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/installer/DynamicInterceptorInstaller.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/metric/domain/http/HttpOutgoingMetricsRegistry.java, agent/agent-plugins/httpclient-okhttp-3.2/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/RealCall$GetResponseWithInterceptorChain.java
=> Fix bugs around okhttp3

agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/installer/DynamicInterceptorInstaller.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/aop/BeanMethodAopInstaller.java, dev/spotbugs-exclude.xml
=> Fix instrumentation bugs around dynamic interceptors

server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceTopoBuilder.java
If the CLIENT span has children spans, there SHOULD be a LINK in the topo if these child spans have no CLIENT termination.
=> Improve topo

component/component-commons/src/main/java/org/bithon/component/commons/expression/LogicalExpression.java, server/server-commons/src/main/java/org/bithon/server/commons/matcher/IMatcherVisitor.java, server/server-commons/src/main/java/org/bithon/server/commons/matcher/NotMatcher.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/utils/SQLFilterBuilder.java, server/storage/src/main/antlr4/org/bithon/server/datasource/ast/FilterExpression.g4, server/storage/src/main/java/org/bithon/server/storage/common/expression/FilterExpressionASTFactory.java, server/storage/src/test/java/org/bithon/server/storage/datasource/filter/ExpressionFilterTest.java, server/web-app/src/main/resources/static/js/chart-component.js, server/web-app/src/main/resources/static/js/component/table/component.js, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/FilterExpressionToFilters.java
=> NOT expression support

server/storage/src/main/java/org/bithon/server/storage/datasource/DataSourceSchemaManager.java, server/web-app/src/main/java/org/bithon/server/webapp/services/DashboardManager.java
=> Fix circular reference

agent/agent-controller/src/main/java/org/bithon/agent/controller/cmd/JvmCommand.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/loader/CascadingClassLoader.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/loader/JarClassLoader.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/loader/PluginClassLoader.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/loader/PluginClassLoaderManager.java, agent/agent-plugins/apache-druid/src/main/java/org/bithon/agent/plugin/apache/druid/interceptor/QueryLifecycle$Initialize.java, agent/agent-plugins/httpclient-okhttp-3.2/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/RealCall$GetResponseWithInterceptorChain.java
=> Fix NoClassDefFoundError

component/component-commons/src/main/java/org/bithon/component/commons/expression/LiteralExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/LogicalExpression.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/utils/Expression2Sql.java, server/storage/src/main/java/org/bithon/server/storage/common/expression/optimizer/ExpressionOptimizer.java, server/storage/src/main/java/org/bithon/server/storage/web/Dashboard.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/optimizer/ExpressionOptimizerTest.java, server/web-app/src/main/java/org/bithon/server/webapp/services/DashboardManager.java, server/web-app/src/main/java/org/bithon/server/webapp/ui/DashboardController.java, server/web-app/src/main/java/org/bithon/server/webapp/ui/LogController.java, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/time-interval/component.js, server/web-app/src/main/resources/templates/log/detail.html, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/FilterExpressionToFilters.java
1. improves the logical expressions
2. use integer instead of true/false literal
3. allow time-interval at fe side to be precise of seconds
4. server side sort for pagnated list
5. integrate log store filter in log page
6. use InvalidExpressionException instead of RuntimeException
=> query improvement

server/service-discovery/client/pom.xml, server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/ErrorResponseDecoder.java, server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/ServiceBroadcastInvoker.java, server/web-app/src/main/java/org/bithon/server/webapp/security/JwtAuthenticationFilter.java, server/web-service/pom.xml, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/AgentServiceProxyFactory.java
=> Fix diagnosis

server/server-commons/src/main/java/org/bithon/server/commons/UrlUtils.java, server/server-commons/src/test/java/org/bithon/server/commons/UrlUtilsTest.java
=> Fix dead loop

.gitmodules, pom.xml, server/opentelemetry/pom.xml
Make it out of the root project so that no need to change versions in custom repo
=> Adjust otel proto module

server/web-app/src/main/resources/static/js/component/auto-refresher/component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/table/component.js, server/web-app/src/main/resources/static/js/component/time-interval/component.js, server/web-app/src/main/resources/static/js/component/time-span-selector/component.js, server/web-app/src/main/resources/static/js/page/event/page.js, server/web-app/src/main/resources/static/js/page/trace/page.js, server/web-app/src/main/resources/static/js/page/trace/profiling-page.js, server/web-app/src/main/resources/templates/app/app-layout.html, server/web-app/src/main/resources/templates/app/topo.html, server/web-app/src/main/resources/templates/diagnosis/diagnosis.html, server/web-app/src/main/resources/templates/log/detail.html, server/web-app/src/main/resources/templates/trace/search.html
Not the best solution but the least effort to show the instances of an application for efficiency.
=> Add instance list to diagosis page

component/component-commons/src/main/java/org/bithon/component/commons/expression/ArrayAccessExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/IExpressionVisitor.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/IExpressionVisitor2.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/MapAccessExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/serialization/ExpressionSerializer.java, server/storage/src/main/antlr4/org/bithon/server/datasource/ast/Expression.g4, server/storage/src/main/java/org/bithon/server/storage/common/expression/ExpressionASTBuilder.java, server/storage/src/main/java/org/bithon/server/storage/common/expression/optimizer/ExpressionOptimizer.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/ExpressionSerializerTest.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/IdentifierExpressionTest.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/optimizer/ExpressionOptimizerTest.java, server/web-app/src/main/resources/dashboard/kafka-consumer-metrics.json, server/web-app/src/main/resources/dashboard/kafka-network-metrics.json, server/web-app/src/main/resources/static/js/component/table/component.js, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/FilterExpressionToFilters.java
See commits for what has been changed.
=> filter improvement

agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/installer/InterceptorInstaller.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/plugin/PluginResolver.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/dispatcher/task/DispatchTask.java, agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/ApacheHttpClientPlugin.java, agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/interceptor/DefaultClientConnectionOperator$OpenConnection.java, agent/agent-plugins/httpclient-apache/src/main/java/org/bithon/agent/plugin/httpclient/apache/interceptor/DefaultHttpClientConnectionOperator$Connect.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/JdkHttpClientPlugin.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpURLConnection$Connect.java, agent/agent-plugins/httpclient-okhttp-3.2/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/OkHttp32HttpClientPlugin.java, agent/agent-plugins/httpclient-okhttp-3.2/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/RealConnection$Connect.java
=> trace http connect

agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/config/TraceConfig.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpClient$ParseHTTP.java, agent/agent-plugins/httpclient-jetty/src/main/java/org/bithon/agent/plugin/httpclient/jetty/HttpRequest$Send.java, agent/agent-plugins/httpclient-okhttp-3.2/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/RealCall$GetResponseWithInterceptorChain.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientFinalizer$ResponseConnection.java
=> Add responses headers for webclient

server/sink/src/main/java/org/bithon/server/kafka/AbstractKafkaConsumer.java, server/sink/src/main/java/org/bithon/server/kafka/KafkaConsumerManager.java, server/sink/src/main/java/org/bithon/server/sink/SinkAutoConfiguration.java, server/sink/src/main/java/org/bithon/server/sink/event/EventInputSource.java, server/sink/src/main/java/org/bithon/server/sink/event/MetricOverEventHandler.java, server/sink/src/main/java/org/bithon/server/sink/metrics/LocalMetricSink.java, server/sink/src/main/java/org/bithon/server/sink/metrics/MetricInputSource.java, server/sink/src/main/java/org/bithon/server/sink/metrics/MetricMessageHandler.java, server/sink/src/main/java/org/bithon/server/sink/tracing/metrics/MetricOverSpanInputSource.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/storage/TableCreator.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/storage/TraceStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/storage/web/DashboardStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/IndexedTagQueryBuilder.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcReader.java, server/storage/src/main/java/org/bithon/server/storage/StorageModuleAutoConfiguration.java, server/storage/src/main/java/org/bithon/server/storage/common/provider/StorageProviderManager.java, server/storage/src/main/java/org/bithon/server/storage/tracing/ITraceReader.java, server/web-app/src/main/java/org/bithon/server/webapp/WebAppAutoConfiguration.java, server/web-service/src/main/java/org/bithon/server/web/service/event/api/EventApi.java
1. different storages can be deployed independently totally
2. update the cluster mode support of ck storage
=> Improve module independency in different deployment

agent/agent-distribution/resources/agent.yml, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/propagation/ChainedTraceContextExtractor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/server/interceptor/ServerCallInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/server/interceptor/ServerImplBuilder$Build.java, component/component-commons/src/main/java/org/bithon/component/commons/tracing/Tags.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/transform/TraceSpanTransformer.java, server/server-starter/src/main/resources/application-pipeline-to-local.yml, server/web-app/src/main/resources/static/js/component/trace-list-component.js, server/web-service/src/main/java/org/bithon/server/web/service/agent/api/AgentConfigurationApi.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceTopoBuilder.java
1. add more attributes in the GRPC span
2. optimize the topo name for GRPC
=> Improve GRPC plugin

pom.xml, server/agent-controller/pom.xml, server/agent-controller/src/main/java/org/bithon/server/agent/controller/api/AgentProxyApi.java, server/agent-controller/src/main/java/org/bithon/server/agent/controller/config/AgentControllerConfig.java, server/agent-controller/src/main/java/org/bithon/server/agent/controller/config/PermissionConfig.java, server/agent-controller/src/main/java/org/bithon/server/agent/controller/config/PermissionRule.java, server/agent-controller/src/main/java/org/bithon/server/agent/controller/service/AgentControllerServer.java, server/agent-controller/src/main/java/org/bithon/server/agent/controller/service/AgentSettingFetcher.java, server/collector/src/main/java/org/bithon/server/collector/CollectorAutoConfiguration.java, server/collector/src/main/java/org/bithon/server/collector/brpc/BrpcCollectorConfig.java, server/collector/src/main/java/org/bithon/server/collector/brpc/BrpcCollectorServer.java, server/collector/src/main/java/org/bithon/server/collector/brpc/BrpcEventCollector.java, server/collector/src/main/java/org/bithon/server/collector/brpc/BrpcMetricCollector.java, server/collector/src/main/java/org/bithon/server/collector/brpc/BrpcTraceCollector.java, server/collector/src/main/java/org/bithon/server/collector/http/MetricHttpCollector.java, server/collector/src/main/java/org/bithon/server/collector/http/TraceHttpCollector.java, server/collector/src/main/java/org/bithon/server/collector/otel/OtelHttpTraceCollector.java, server/collector/src/main/java/org/bithon/server/collector/otel/OtelSpanConverter.java, server/server-starter/pom.xml, server/web-service/pom.xml, server/web-service/src/main/java/org/bithon/server/web/service/agent/api/AgentConfigurationApi.java, server/web-service/src/main/java/org/bithon/server/web/service/sentinel/SentinelRuleApi.java
=> Move agent controller out of collector

server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/SecondaryIndex.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/TableCreator.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/meta/MetadataStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/meta/SchemaStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/trace/TraceStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/web/DashboardStorage.java
Fixes #713 to celebrate the chinese new year
=> create secondary indexes

agent/agent-core/src/main/java/org/bithon/agent/configuration/Binder.java, agent/agent-core/src/main/java/org/bithon/agent/configuration/PluginConfiguration.java, agent/agent-core/src/test/java/org/bithon/agent/configuration/TestConfigurationManager.java, agent/agent-plugins/spring-bean/src/main/resources/org.bithon.agent.plugin.spring.bean.yml
=> Fix mapping to a simple data type

agent/agent-plugins/apache-druid/pom.xml, server/agent-controller/src/main/java/org/bithon/server/agent/controller/api/AgentProxyApi.java, server/service-discovery/declaration/src/main/java/org/bithon/server/discovery/declaration/controller/IAgentProxyApi.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/api/AgentDiagnosisApi.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/AgentServiceProxyFactory.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/InstanceTable.java, server/web-service/src/main/java/org/bithon/server/web/service/common/sql/SqlExecutionEngine.java
=> push down the 'instance' filter

agent/agent-core/src/main/java/org/bithon/agent/config/AopConfig.java, agent/agent-core/src/main/java/org/bithon/agent/config/AppConfig.java, agent/agent-core/src/main/java/org/bithon/agent/configuration/ConfigurationManager.java, agent/agent-core/src/main/java/org/bithon/agent/configuration/validation/RegExpr.java, agent/agent-core/src/main/java/org/bithon/agent/configuration/validation/Validator.java, agent/agent-core/src/main/java/org/bithon/agent/starter/AgentStarter.java, agent/agent-core/src/test/java/org/bithon/agent/configuration/TestConfigurationManager.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/InterceptorTypeResolver.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/plugin/PluginResolver.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/bytecode/ProxyClassGenerator.java, component/component-commons/src/main/java/org/bithon/component/commons/utils/HumanReadablePercentage.java, doc/configuration/agent/README.md, doc/configuration/configuration.md, doc/configuration/server/configuration-collector.md, doc/faq/README.md, doc/metrics/http-outgoing/README.md, doc/tracing/README.md, server/service-discovery/README.md
1. check the application.name and application.env property value to prevent illegal configuration
2. improve comments & docs
3. print the shorten plugin package name instead of the plugin class name for bettern understanding
4. improve robus of configuration api
=> improvements over docs/code

server/web-app/src/main/resources/static/js/component/dashboard.js, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/DataSourceService.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/TimeSeriesMetric.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/TimeSeriesQueryResult.java
=> Fix extra value in the time series chart

agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/ListenerConsumer$Ctor.java
=> Fix bug #748

agent/agent-observability/src/main/java/org/bithon/agent/observability/logging/LogPatternInjector.java, agent/agent-observability/src/test/java/org/bithon/agent/observability/logging/LogPatternInjectorTest.java
There variable name has a format of default value, use the regular expression to check if the variable has been injected.
=> Improve the traceId injection

server/pipeline/src/main/java/org/bithon/server/pipeline/common/kafka/AbstractKafkaConsumer.java, server/pipeline/src/main/java/org/bithon/server/pipeline/event/receiver/KafkaEventReceiver.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/receiver/KafkaMetricReceiver.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/receiver/KafkaTraceReceiver.java, server/server-commons/pom.xml, server/server-commons/src/main/java/org/bithon/server/commons/logging/RateLimitLogger.java, server/server-commons/src/test/java/org/bithon/server/commons/logging/RateLimitLoggerTest.java
1. fix the injection error when deserializing objects from kafka message
2. apply rate limit on the error messages from kafka message processing
=> Fix injection error

server/storage/src/main/antlr4/org/bithon/server/datasource/ast/Expression.g4, server/storage/src/test/java/org/bithon/server/storage/common/expression/ExpressionSerializerTest.java
=> Fix expression precedence

README.md, agent/agent-observability/src/main/java/org/bithon/agent/observability/metric/domain/redis/RedisClientMetrics.java, agent/agent-plugins/apache-httpcomponents4/src/main/java/org/bithon/agent/plugin/apache/httpcomponents4/interceptor/DefaultClientConnectionOperator$OpenConnection.java, agent/agent-plugins/apache-httpcomponents4/src/main/java/org/bithon/agent/plugin/apache/httpcomponents4/interceptor/DefaultHttpClientConnectionOperator$Connect.java, agent/agent-plugins/httpclient-jdk/src/main/java/org/bithon/agent/plugin/httpclient/jdk/interceptor/HttpURLConnection$Connect.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/LettuceAsyncContext.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/LettucePlugin.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/AbstractRedisAsyncCommands$Dispatch.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/AsyncCommand$Complete.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/AsyncCommand$Encode.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/Command$Execute.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/CommandHandler$Decode.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/ConnectionContext.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/DefaultConnectionFuture$Get.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/LettuceConnection$Ctor.java, agent/agent-plugins/redis-lettuce-5.x/src/main/java/org/bithon/agent/plugin/redis/lettuce/interceptor/RedisClient$Connect.java, component/component-commons/src/main/java/org/bithon/component/commons/utils/ReflectionUtils.java, server/web-app/src/main/resources/dashboard/redis-metrics.json, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceTopoBuilder.java
=> Improve metrics and trace for lettuce

server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/exception/RetryableExceptions.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/trace/LoadBalancedTraceWriter.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/trace/TraceStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/trace/TraceWriter.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/writer/IndexTableJdbcWriter.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/writer/MappingTableJdbcWriter.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/writer/SpanTableJdbcWriter.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/writer/TraceJdbcWriter.java
Save the INSERTs and network traffic
=> Use materialized view

server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/web-app/src/main/resources/static/js/component/table.js, server/web-app/src/main/resources/static/js/component/trace-list-component.js, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/GeneralQueryResponse.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/GetTraceListResponse.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/TraceApi.java
=> Improves pagination performance over large scale data set

component/component-commons/src/main/java/org/bithon/component/commons/expression/LogicalExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/optimzer/ExpressionOptimizer.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/serialization/ExpressionSerializer.java, component/component-commons/src/test/java/org/bithon/component/commons/expression/optimizer/ExpressionOptimizerTest.java, server/storage-jdbc-clickhouse/src/test/java/org/bithon/server/storage/jdbc/clickhouse/common/optimizer/HasTokenFunctionOptimizerTest.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/dialect/Expression2Sql.java
reduce the nest so that the generated sql is more readable
=> Flatten logical expressions

component/component-commons/src/main/java/org/bithon/component/commons/utils/StringUtils.java, server/server-commons/src/main/java/org/bithon/server/commons/utils/UrlUtils.java
extract method for internal branches use
=> Extract kv method

README.md, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/debug/AopDebugger.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/ClientCallInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/ManagedChannelImplBuilder$Build.java, agent/agent-plugins/grpc/src/main/resources/org.bithon.agent.plugin.grpc.yml, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/jdk/thread/interceptor/ForkJoinPool$Ctor.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/jdk/thread/utils/ThreadPoolNameHelper.java, server/pipeline/src/main/java/org/bithon/server/pipeline/event/exporter/KafkaEventExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/MetricPipeline.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/exporter/ToKafkaExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/exporter/ToKafkaExporter.java
=> fix and improvement

agent/agent-core/src/main/java/org/bithon/agent/configuration/source/PropertySource.java, agent/agent-core/src/test/java/org/bithon/agent/configuration/TestConfigurationManager.java, agent/agent-core/src/test/resources/conf/external.yml
=> Fix merge of array nodes

server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/DiscoveredServiceInvoker.java, server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/DiscoveryClientAutoConfiguration.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/AgentSchema.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/AgentServiceProxyFactory.java
=> Defer instantiation of discovery client

dev/forbidden-apis-bithon.txt, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/alerting/AlertObjectJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/alerting/AlertRecordJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/alerting/NotificationChannelJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/meta/SchemaJdbcStorage.java, server/web-app/src/main/resources/templates/alerting/record/records.html
=> Forbide use of fetchCount

component/component-commons/src/main/java/org/bithon/component/commons/expression/LiteralExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/Functions.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/IFunction.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/builtin/AggregateFunction.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/builtin/NumberFunction.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/builtin/StringFunction.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/builtin/TimeFunction.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/optimzer/ExpressionOptimizer.java, component/component-commons/src/test/java/org/bithon/component/commons/expression/optimizer/ExpressionOptimizerTest.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/ExpressionASTBuilderTest.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/ExpressionTest.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/optimizer/ExpressionOptimizerTest.java
=> support now()

server/collector/src/main/java/org/bithon/server/collector/http/TraceHttpCollector.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/receiver/KafkaTraceReceiver.java, server/server-starter/src/main/java/org/bithon/server/starter/config/ObjectMapperConfigurer.java, server/storage/src/main/java/org/bithon/server/storage/tracing/TraceSpan.java
=> Avoid NPE during pipeline processing

agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/ClientCallInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/server/interceptor/ServerCallInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/utils/MessageUtils.java, component/component-commons/src/main/java/org/bithon/component/commons/tracing/Tags.java
=> Add grpc message size

agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcMessageConverter.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/impl/TracingContext.java, agent/agent-plugins/bithon-sdk/src/main/java/org/bithon/agent/plugin/bithon/sdk/interceptor/MetricsRegistryDelegate.java, agent/agent-plugins/httpclient-reactor/src/main/java/org/bithon/agent/plugin/httpclient/reactor/HttpClientContext.java, agent/agent-plugins/httpclient-reactor/src/main/java/org/bithon/agent/plugin/httpclient/reactor/HttpClientReactorPlugin.java, agent/agent-plugins/httpclient-reactor/src/main/java/org/bithon/agent/plugin/httpclient/reactor/interceptor/HttpClientConfig$DefaultConnectionObserver.java, agent/agent-plugins/httpclient-reactor/src/main/java/org/bithon/agent/plugin/httpclient/reactor/interceptor/HttpClientFinalizer$Connect.java, agent/agent-plugins/httpclient-reactor/src/main/java/org/bithon/agent/plugin/httpclient/reactor/interceptor/HttpClientFinalizer$Send.java, dev/spotbugs-exclude.xml
two bugs caused by #863 
1. response time metric is not correct if no span on current thread context
2. it causes connection pool invalidation due
1. improved the code in metric collection
=> Fix reactor-http-client bug

server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/metric/absolute/EqualPredicate.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/metric/absolute/NotEqualPredicate.java
=> Fix equal predicate bug

agent/agent-main/src/main/java/org/bithon/agent/main/Main.java, agent/agent-plugins/httpclient-okhttp-3.2/src/main/java/org/bithon/agent/plugin/httpclient/okhttp32/OkHttp32HttpClientPlugin.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/QueryExpressionBuilder.java
1. prevent re-initialization in case of misconfiguration of -javaagent
2. do not load agent under some cases when JAVA_TOOL_OPTIONS is set
3. support okhttp3.12
4. Fix startsWith/endsWith operator when using ck
=> improvement over agent

agent/agent-observability/src/main/java/org/bithon/agent/observability/metric/domain/web/HttpIncomingFilter.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/builtin/StringFunction.java, server/storage/src/test/java/org/bithon/server/storage/common/expression/FunctionsTest.java
=> Http endpoint filter

README.md, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/plugin/PluginResolver.java, agent/agent-plugins/openfeign/pom.xml, agent/agent-plugins/openfeign/src/main/java/org/bithon/agent/plugin/openfeign/OpenFeignPlugin.java, agent/agent-plugins/openfeign/src/main/java/org/bithon/agent/plugin/openfeign/interceptor/FeignInvocationContext.java, agent/agent-plugins/openfeign/src/main/java/org/bithon/agent/plugin/openfeign/interceptor/SynchronousMethodHandler$Invoke.java, agent/agent-plugins/openfeign/src/main/java/org/bithon/agent/plugin/openfeign/interceptor/SynchronousMethodHandlerFactory$Create.java, agent/agent-plugins/pom.xml, agent/agent-plugins/spring-webmvc/pom.xml, agent/agent-plugins/spring-webmvc/src/main/java/org/bithon/agent/plugin/spring/webmvc/SpringWebMvcPlugin.java, agent/agent-plugins/spring-webmvc/src/main/java/org/bithon/agent/plugin/spring/webmvc/controller/InvocableHandlerMethod$DoInvoke.java, agent/agent-plugins/spring-webmvc/src/main/java/org/bithon/agent/plugin/spring/webmvc/rs/RestTemplate$Execute.java, agent/agent-plugins/spring-webmvc/src/main/java/org/bithon/agent/plugin/spring/webmvc/rs/RestTemplate$HandleResponse.java
1. move feign out of spring.mvc
2. rename spring.mvc to spring.webmvc
=> rename spring plugins

server/pipeline/src/main/java/org/bithon/server/pipeline/common/pipeline/AbstractPipeline.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/TracePipeline.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/TracePipelineConfig.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/exporter/ToTraceStorageExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/mapping/CurrentTraceIdExtractor.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/mapping/NameValueExtractor.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/mapping/TraceIdMappingBatchExtractor.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/mapping/URIParameterExtractor.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/mapping/UpstreamTraceIdExtractor.java, server/pipeline/src/test/java/org/bithon/server/pipeline/tracing/mapping/URIParameterExtractorTest.java
=> Support to change mappings on the fly

agent/agent-plugins/redis-jedis-4.x/src/main/java/org/bithon/agent/plugin/redis/jedis4/interceptor/OnCommand.java
A follow up of #884 which fixed the problem on jedis2 and jedis3
=> Make sure jedis4 client metrics are recorded if tracing is not enabled

server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/trace/TraceStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/reader/TraceJdbcReader.java, server/storage/src/main/java/org/bithon/server/storage/datasource/query/IDataSourceReader.java, server/storage/src/main/java/org/bithon/server/storage/tracing/ITraceReader.java, server/storage/src/main/java/org/bithon/server/storage/tracing/TraceTableSchema.java, server/storage/src/main/java/org/bithon/server/storage/tracing/reader/TraceFilterSplitter.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/TraceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceService.java
so that at the client side, the APIs are unified. getTraceList and getTraceDistribution are also marked as deprecated.
=> Use data source api to replace trace api

agent/agent-core/src/main/java/org/bithon/agent/configuration/ObjectMapperConfigurer.java, agent/agent-core/src/test/java/org/bithon/agent/configuration/TestConfigurationManager.java, component/component-commons/src/main/java/org/bithon/component/commons/utils/HumanReadablePercentage.java, component/component-commons/src/test/java/org/bithon/component/commons/utils/HumanReadablePercentageTest.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/parser/AlertExpressionASTParser.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/serializer/AlertExpressionSerializer.java, server/alerting/common/src/test/java/org/bithon/server/alerting/common/serializer/AlertExpressionSerializerTest.java, server/metric-expression/src/main/java/org/bithon/server/metric/expression/MetricExpression.java, server/metric-expression/src/main/java/org/bithon/server/metric/expression/MetricExpressionASTBuilder.java, server/metric-expression/src/test/java/org/bithon/server/metric/expression/MetricExpressionASTBuilderTest.java, server/pipeline/src/test/java/org/bithon/server/pipeline/common/transformer/ProbabilisticSamplerTransformTest.java, server/server-commons/src/main/java/org/bithon/server/commons/serializer/HumanReadablePercentageDeserializer.java, server/server-commons/src/main/java/org/bithon/server/commons/serializer/HumanReadablePercentageSerializer.java, server/server-commons/src/test/java/org/bithon/server/commons/serializer/HumanReadablePercentageSerializerTest.java, server/storage-jdbc/src/test/java/org/bithon/server/storage/jdbc/metric/QueryExpressionBuilderTest.java, server/storage/src/main/java/org/bithon/server/storage/common/expression/ExpressionASTBuilder.java
also use more understandable phase 'offset'
=> Disable absolute comparison when offset is giving

component/component-commons/src/main/java/org/bithon/component/commons/utils/HumanReadableDuration.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/metric/relative/AbstractRelativeThresholdPredicate.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/metric/relative/RelativeGTEPredicate.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/metric/relative/RelativeGTPredicate.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/metric/relative/RelativeLTEPredicate.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/metric/relative/RelativeLTPredicate.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/result/IEvaluationOutput.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/evaluator/result/RelativeComparisonEvaluationOutput.java, server/alerting/common/src/main/java/org/bithon/server/alerting/common/model/AlertRule.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/EvaluatorModuleAutoConfiguration.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/evaluator/AlertEvaluator.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/repository/AlertRepository.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/repository/IAlertChangeListener.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/storage/local/AlertStateLocalMemoryStorage.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/storage/redis/AlertStateRedisStorage.java, server/alerting/evaluator/src/test/java/org/bithon/server/alerting/evaluator/evaluation/AlertRuleEvaluatorTest.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/parameter/CreateAlertRuleRequest.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/biz/AlertCommandService.java, server/alerting/notification/src/main/java/org/bithon/server/alerting/notification/channel/http/HttpNotificationChannel.java, server/alerting/notification/src/main/java/org/bithon/server/alerting/notification/config/NotificationProperties.java, server/metric-expression/src/main/antlr4/org/bithon/server/metric/expression/MetricExpression.g4, server/metric-expression/src/main/java/org/bithon/server/metric/expression/api/MetricQueryApi.java, server/metric-expression/src/test/java/org/bithon/server/metric/expression/MetricExpressionASTBuilderTest.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/QueryResponse.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/TimeSeriesQueryResult.java
1. Support negative percentage
2. Fix relative comparison
3. Add experimental API for metric expression
=> Improve relative comparison

server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/GetTraceByIdResponse.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/TraceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/api/TraceSpanBo.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceService.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceTopoBuilder.java
add depth/index/childRef/gap and fix exception status on topo
=> Improve trace response for better FE processing

server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/AlertChannelApi.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/AlertCommandApi.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/AlertQueryApi.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/parameter/CreateAlertRuleRequest.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/parameter/UpdateAlertRuleRequest.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/biz/AlertExpressionSuggester.java, server/alerting/notification/src/main/java/org/bithon/server/alerting/notification/api/NotificationApiImpl.java, server/server-commons/src/main/java/org/bithon/server/commons/utils/SqlLikeExpression.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/ClickHouseSqlDialect.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/alerting/NotificationChannelStorage.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/optimizer/ClickHouseExpressionOptimizer.java, server/storage-jdbc-h2/src/main/java/org/bithon/server/storage/jdbc/h2/H2SqlDialect.java, server/storage-jdbc-mysql/src/main/java/org/bithon/server/storage/jdbc/mysql/MySQLSqlDialect.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/alerting/AlertObjectJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/alerting/NotificationChannelJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/dialect/Expression2Sql.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/storage/src/main/java/org/bithon/server/storage/alerting/IAlertNotificationChannelStorage.java, server/storage/src/main/java/org/bithon/server/storage/datasource/query/Query.java, server/storage/src/main/java/org/bithon/server/storage/event/EventTableSchema.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/QueryResponse.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/QueryConverter.java
1. support passing '*' as field from the client
2. support to return meta data of selected column
3. fix forgotten sql dialect's transformation
=> Improve query processing

agent/agent-plugins/redis-jedis-2.x/src/main/java/org/bithon/agent/plugin/redis/jedis2/interceptor/OnCommand.java, agent/agent-plugins/redis-jedis-3.x/src/main/java/org/bithon/agent/plugin/redis/jedis3/interceptor/OnCommand.java
1.Correctly obtain redis db object
2.Correctly calculate ResponseTime
=> fix bug for issues 879

server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/evaluator/AlertEvaluator.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/biz/AlertCommandService.java, server/alerting/notification/src/main/java/org/bithon/server/alerting/notification/channel/http/HttpNotificationChannel.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/alerting/NotificationChannelStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/alerting/AlertObjectJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/alerting/NotificationChannelJdbcStorage.java
1. add a test channel for h2
2. fix npe when issuing resolved notification
=> Fix some bugs

agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/impl/TracingContext.java, server/web-app/src/main/resources/dashboard/kafka-consumer-metrics.json, server/web-app/src/main/resources/dashboard/kafka-network-metrics.json, server/web-app/src/main/resources/dashboard/kafka-producer-metrics.json, server/web-app/src/main/resources/dashboard/redis-metrics.json
=> Fix context copy

README.md, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/precondition/PropertyFileValuePrecondition.java, agent/agent-plugins/apache-zookeeper/pom.xml, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ClientCnxn$Ctor.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ClientCnxn$FinishPacket.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ClientCnxn$SubmitRequest.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ClientCnxnPacket$CreateBB.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ClientCnxnSendThread$ReadResponse.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ClientCnxnSocket$Connect.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/IOMetrics.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/OpNameLookup.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/RequestHeader$Ctor.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ZKConnectionContext.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ZooKeeperPlugin.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/metrics/ZKClientMetricRegistry.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/metrics/ZKClientMetrics.java, agent/agent-plugins/jdbc/apache-derby/pom.xml, agent/agent-plugins/jdbc/apache-derby/src/main/java/org/bithon/agent/plugin/jdbc/apache/derby/ClientConnection$Ctor.java, agent/agent-plugins/jdbc/apache-derby/src/main/java/org/bithon/agent/plugin/jdbc/apache/derby/ClientPreparedStatement$Ctor.java, agent/agent-plugins/jdbc/apache-derby/src/main/java/org/bithon/agent/plugin/jdbc/apache/derby/ClientPreparedStatement$Execute.java, agent/agent-plugins/jdbc/apache-derby/src/main/java/org/bithon/agent/plugin/jdbc/apache/derby/ClientStatement$Execute.java, agent/agent-plugins/jdbc/apache-derby/src/main/java/org/bithon/agent/plugin/jdbc/apache/derby/ClientStatement$ExecuteBatch.java, agent/agent-plugins/jdbc/apache-derby/src/main/java/org/bithon/agent/plugin/jdbc/apache/derby/DerbyPlugin.java, agent/agent-plugins/pom.xml, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/topo/TopoTransformers.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/topo/ZooKeeperClientTopoTransformer.java, server/pipeline/src/main/resources/schema/zookeeper-client-metrics.json, server/server-commons/src/main/java/org/bithon/server/commons/utils/DbUtils.java, server/storage/src/main/java/org/bithon/server/storage/meta/EndPointType.java, server/web-app/src/main/resources/dashboard/zookeeper-client-metrics.json
=> Derby JDBC client & ZooKeeper client support

docker/Dockerfile-agent, docker/Dockerfile-server
1. speedup building
2. switch to alpine base image for agent
3. support BUILD_FROM_SOURCE build arg for agent
=> Optimize docker building

agent/agent-plugins/apache-druid/pom.xml, agent/agent-plugins/apache-druid/src/main/java/org/bithon/agent/plugin/apache/druid/ApacheDruidPlugin.java, agent/agent-plugins/apache-druid/src/main/java/org/bithon/agent/plugin/apache/druid/interceptor/ServiceClientImpl$AsyncRequest.java, agent/agent-plugins/httpserver/jetty/src/main/java/org/bithon/agent/plugin/httpserver/jetty/interceptor/HttpChannel$Handle.java, component/component-commons/src/main/java/org/bithon/component/commons/tracing/Tags.java
=> record query parameters for jetty

agent/agent-plugins/apache-kafka-3.7/pom.xml, agent/agent-plugins/apache-kafka-3.7/src/main/java/org/bithon/agent/plugin/apache/kafka37/Kafka37Plugin.java, agent/agent-plugins/apache-kafka-3.7/src/main/java/org/bithon/agent/plugin/apache/kafka37/consumer/interceptor/KafkaConsumer$Ctor.java, agent/agent-plugins/apache-kafka-3.9/src/main/java/org/bithon/agent/plugin/apache/kafka39/Kafka39Plugin.java, agent/agent-plugins/apache-kafka-3.9/src/main/java/org/bithon/agent/plugin/apache/kafka39/consumer/interceptor/KafkaConsumer$Ctor.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/KafkaPlugin.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/ListenerConsumer$Ctor.java
=> Fix NPE for Kafka 3.7 and above

agent/agent-controller/src/main/java/org/bithon/agent/controller/cmd/JvmCommand.java, agent/agent-plugins/apache-zookeeper/src/main/java/org/bithon/agent/plugin/apache/zookeeper/ZooKeeperPlugin.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/cmd/IJvmCommand.java, component/component-brpc/src/main/java/org/bithon/component/brpc/exception/ServiceNotFoundException.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/InvocationManager.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/ServiceInvocationRunnable.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/in/ServiceResponseMessageIn.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/out/ServiceResponseMessageOut.java, component/component-brpc/src/test/java/org/bithon/component/brpc/BrpcRpcTest.java, doc/diagnosis/README.md, server/service-discovery/client/src/main/java/org/bithon/server/discovery/client/ErrorResponseDecoder.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/api/AgentDiagnosisApi.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/AgentSchema.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/AgentServiceProxyFactory.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/JmxBeanAttributeTable.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/JmxBeanAttributeValueTable.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/JmxBeanTable.java
=> Support JMX bean inspection and realtime monitoring

README.md, agent/agent-observability/src/main/java/org/bithon/agent/observability/metric/model/AbstractMetricStorage.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/context/GrpcClientMetricStorage.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/context/ObservabilityContext.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/ClientCallInterceptor.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/metrics/GrpcMetrics.java, agent/agent-plugins/jdbc/mysql8/pom.xml, component/component-brpc/src/test/java/org/bithon/component/brpc/BrpcRpcTest.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/topo/GrpcClientTopoTransformer.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/topo/TopoTransformers.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/transform/TraceSpanTransformer.java, server/pipeline/src/main/resources/schema/grpc-client-metrics.json, server/server-starter/pom.xml, server/server-starter/src/main/java/org/bithon/server/starter/config/ObjectMapperConfigurer.java, server/storage/src/main/java/org/bithon/server/storage/meta/EndPointType.java, server/storage/src/main/java/org/bithon/server/storage/tracing/TraceTableSchema.java, server/storage/src/main/resources/dashboard/grpc-client-metrics.json, server/web-service/src/main/java/org/bithon/server/web/service/topo/api/TopoApi.java, server/web-service/src/main/java/org/bithon/server/web/service/topo/service/EndpointBo.java, server/web-service/src/main/java/org/bithon/server/web/service/topo/service/Link.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceTopoBuilder.java
=> Add grpc client metrics

agent/agent-distribution/resources/agent.yml, agent/agent-plugins/httpserver/jetty-12/src/main/java/org/bithon/agent/plugin/httpserver/jetty12/interceptor/HandlerInvoker$CompleteStream.java, agent/agent-plugins/httpserver/jetty/src/main/java/org/bithon/agent/plugin/httpserver/jetty/interceptor/HttpChannel$OnCompleted.java, agent/agent-plugins/httpserver/tomcat/src/main/java/org/bithon/agent/plugin/httpserver/tomcat/interceptor/StandardHostValve$Invoke.java, agent/agent-plugins/httpserver/undertow/src/main/java/org/bithon/agent/plugin/httpserver/undertow/interceptor/HttpServerExchangeDispatch.java, agent/agent-plugins/jdbc/postgresql/src/main/java/org/bithon/agent/plugin/jdbc/postgresql/PgConnection$Ctor.java, component/component-commons/src/main/java/org/bithon/component/commons/tracing/Tags.java, server/server-commons/src/test/java/org/bithon/server/commons/utils/DbUtilsTest.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/setting/SettingStorage.java, server/storage/src/main/resources/dashboard/application-overview.json, server/storage/src/main/resources/dashboard/http-incoming-metrics.json, server/storage/src/main/resources/dashboard/http-outgoing-metrics.json, server/storage/src/main/resources/dashboard/jvm-metrics.json, server/web-service/src/main/java/org/bithon/server/web/service/dashboard/DashboardManager.java
1. update default dashboard
2. add more http request headers to record
3. record configured http server response headers
4. fix NULL when node list is given in JDBC
=> A bunch of improvements

agent/agent-controller/src/main/java/org/bithon/agent/controller/cmd/InstrumentationCommand.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/advice/AfterAdvice.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/advice/AroundAdvice.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/advice/AroundConstructorAdvice.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/advice/BeforeAdvice.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/advice/ConstructorAfterAdvice.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/InterceptorSupplier.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/declaration/AbstractInterceptor.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/cmd/IInstrumentationCommand.java, doc/diagnosis/README.md, server/web-service/src/main/java/org/bithon/server/web/service/common/output/JsonCompactOutputFormatter.java
=> Add runtime exception info to interceptor

component/component-commons/src/main/java/org/bithon/component/commons/expression/optimzer/AbstractOptimizer.java, server/server-starter/README.md, server/server-starter/pom.xml, server/server-starter/src/test/java/org/bithon/server/storage/jdbc/common/statement/SelectStatementBuilderTest.java, server/storage-jdbc-h2/src/main/java/org/bithon/server/storage/jdbc/h2/SafeDivisionTransformer.java, server/storage-jdbc-h2/src/test/java/org/bithon/server/storage/jdbc/h2/H2SqlDialectTest.java, server/storage-jdbc-mysql/pom.xml, server/storage-jdbc-mysql/src/main/java/org/bithon/server/storage/jdbc/mysql/SafeDivisionTransformer.java, server/storage-jdbc-mysql/src/test/java/org/bithon/server/storage/jdbc/mysql/MySQLDialectTest.java, server/storage-jdbc-postgresql/src/main/java/org/bithon/server/storage/jdbc/postgresql/SafeDivisionTransformer.java, server/storage-jdbc-postgresql/src/test/java/org/bithon/server/storage/jdbc/postgresql/PostgresqlDialectTest.java, server/storage-jdbc/pom.xml, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/statement/SelectStatementBuilder.java, server/storage/src/main/resources/dashboard/zookeeper-client-metrics.json, server/web-app/src/main/resources/static/js/alert/metrics-component.js, server/web-app/src/main/resources/static/js/component/dashboard.js, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/IDataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/IntervalRequest.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/QueryConverter.java
Part of #911 
Fix bug introduced by #1002 tests are updated to guard changes
=> Remove legacy APIs

server/alerting/notification/src/main/java/org/bithon/server/alerting/notification/channel/http/HttpNotificationChannel.java, server/datasource/reader-jdbc/src/main/java/org/bithon/server/datasource/reader/jdbc/pipeline/JdbcPipelineBuilder.java, server/datasource/reader-jdbc/src/main/java/org/bithon/server/datasource/reader/jdbc/statement/builder/SelectStatementBuilder.java, server/server-starter/src/test/java/org/bithon/server/storage/jdbc/common/statement/builder/SelectStatementBuilderTest.java
=> Fix query bugs

server/metric-expression/src/main/java/org/bithon/server/metric/expression/api/MetricQueryApi.java, server/metric-expression/src/test/java/org/bithon/server/metric/expression/api/MetricQueryApiTest.java
=> Query Bug fix

agent/agent-controller/src/main/java/org/bithon/agent/controller/impl/brpc/BrpcAgentController.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcClient.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcClientBuilder.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcServer.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/InvocationManager.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/ExceptionMessage.java, component/component-brpc/src/main/java/org/bithon/component/brpc/message/in/ServiceResponseMessageIn.java, server/agent-controller/src/main/java/org/bithon/server/agent/controller/api/AgentControllerApi.java, server/agent-controller/src/main/java/org/bithon/server/agent/controller/service/AgentControllerServer.java, server/collector/src/main/java/org/bithon/server/collector/brpc/BrpcCollectorServer.java, server/service-discovery/declaration/src/main/java/org/bithon/server/discovery/declaration/controller/IAgentControllerApi.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/web/DashboardStorage.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/api/AgentDiagnosisApi.java, server/web-service/src/main/java/org/bithon/server/web/service/agent/sql/table/AgentServiceProxyFactory.java, server/web-service/src/main/java/org/bithon/server/web/service/common/output/JsonCompactOutputFormatter.java
=> A bunch of fix around rpc

agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/precondition/PropertyFileValuePrecondition.java, agent/agent-instrumentation/src/test/java/org/bithon/agent/instrumentation/utils/aop/interceptor/precondition/PropertyFileValuePreconditionTest.java, agent/agent-plugins/apache-kafka-2.7/pom.xml, agent/agent-plugins/apache-kafka-2.7/src/main/java/org/bithon/agent/plugin/apache/kafka27/Kafka27Plugin.java, agent/agent-plugins/apache-kafka-2.7/src/main/java/org/bithon/agent/plugin/apache/kafka27/consumer/interceptor/KafkaConsumer$Ctor.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/KafkaPlugin.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/KafkaConsumer$Ctor.java, agent/agent-plugins/pom.xml, dev/spotbugs-exclude.xml
=> Fix support of kafka 2.7.x consumer

agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/plugin/PluginResolver.java
=> Catch ClassFormatError

agent/agent-core/src/main/java/org/bithon/agent/configuration/ConfigurationManager.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/exporter/Exporter.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/exporter/task/BatchMessageQueue.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/Tracer.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/config/HeaderConfig.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/config/TraceConfig.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/ITraceContext.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/TraceContextFactory.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/impl/LoggingTraceContext.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/impl/TracingContext.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/reporter/BatchReporter.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/reporter/DefaultReporter.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/reporter/ITraceReporter.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/reporter/ReporterConfig.java, agent/agent-observability/src/test/java/org/bithon/agent/observability/tracing/sampler/context/propagation/JaegerExtractorTest.java, agent/agent-observability/src/test/java/org/bithon/agent/observability/tracing/sampler/context/propagation/W3CTraceContextExtractorTest.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/server/interceptor/ServerCallInterceptor.java, agent/agent-plugins/mongodb-3.8/src/main/java/org/bithon/agent/plugin/mongodb38/interceptor/DefaultServerConnection$ExecuteProtocol.java, agent/agent-plugins/mongodb/src/main/java/org/bithon/agent/plugin/mongodb/interceptor/DefaultServerConnection.java, component/component-commons/src/main/java/org/bithon/component/commons/tracing/Tags.java
Fixes #1073
A reporter with default batch size 64 is applied for each tracing context.
=> Improve memory usage

agent/agent-observability/src/main/java/org/bithon/agent/observability/metric/collector/jvm/JvmEventMessageBuilder.java, agent/agent-observability/src/test/java/org/bithon/agent/observability/metric/collector/jvm/SanitizerTest.java
Signed-off-by: Frank Chen <frank.chen021@outlook.com>
=> add more keys to sanitize
