FrankChen021/bithon

agent/agent-plugins/logging-log4j2/src/main/java/org/bithon/agent/plugin/log4j2/interceptor/LoggerLogMessage.java, agent/agent-plugins/logging-logback/src/main/java/org/bithon/agent/plugin/logback/interceptor/LoggerCallAppenders.java
```bash
java.lang.NullPointerException
at shaded.com.google.protobuf.Internal.checkNotNull(Internal.java:63)
at shaded.com.google.protobuf.MapField$MutatabilityAwareMap.putAll(MapField.java:339)
at org.bithon.agent.rpc.brpc.event.BrpcEventMessage$Builder.putAllArguments(BrpcEventMessage.java:853)
at org.bithon.agent.dispatcher.brpc.BrpcMessageConverter.from(BrpcMessageConverter.java:235)
at org.bithon.agent.plugin.logback.interceptor.LoggerCallAppenders.onMethodLeave(LoggerCallAppenders.java:62)
```
This is because the plugin is going to send NullPointerException whose message is NULL.
=> Fix NPE in agent

agent/agent-plugins/spring-webflux/README.md, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientFinalizer$ResponseConnection.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/NettyRoutingFilter$Filter.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, dev/spotbugs-exclude.xml
No use of ThreadLocal because Flux/Mono might be scheduled on a different thread from the thread where the entry point is scheduled.
=> Update propagation model in webflux

component/component-commons/src/main/java/org/bithon/component/commons/logging/LoggerFactory.java
=> Catch NoClassDefFoundError when detecting logging framework

agent/agent-bootstrap/src/main/java/org/bithon/agent/bootstrap/loader/AgentClassLoader.java, agent/agent-core/src/main/java/org/bithon/agent/core/aop/interceptor/InterceptorInstaller.java, agent/agent-plugins/apache-druid/pom.xml, agent/agent-plugins/apache-druid/src/main/java/org/bithon/agent/plugin/apache/druid/ApacheDruidPlugin.java, agent/agent-plugins/apache-druid/src/main/java/org/bithon/agent/plugin/apache/druid/interceptor/QueryLifecycle$Initialize.java, agent/agent-plugins/apache-druid/src/main/java/org/bithon/agent/plugin/apache/druid/interceptor/SqlLifecycle$Initialize.java, agent/agent-plugins/httpclient-jetty/src/main/java/org/bithon/agent/plugin/httpclient/jetty/HttpRequest$Send.java, agent/agent-plugins/httpclient-netty/src/main/java/org/bithon/agent/plugin/httpclient/netty/Channels$Write.java, agent/agent-plugins/httpclient-netty3/pom.xml, agent/agent-plugins/httpclient-netty3/src/main/java/org/bithon/agent/plugin/httpclient/netty3/Channels$Write.java, agent/agent-plugins/httpclient-netty3/src/main/java/org/bithon/agent/plugin/httpclient/netty3/NettyHttpClientPlugin.java, agent/agent-plugins/pom.xml, shaded/shaded-jackson/pom.xml
1. Show query in trace, including queryId
2. leverage existing trace mapping to allow search trace by queryId
3. fix the URI in tag for httpClient-jetty and httpClient-netty plugins
4. fix the component name of httpClient-netty which is mis-spelled as httpClient-jetty
5. rename httpClient-netty to httpClient-netty3
=> Well support Apache Druid

agent/agent-core/src/main/java/org/bithon/agent/core/tracing/context/Tags.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/ContextHandlerDoHandle.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/HttpChannel$Handle.java, agent/agent-plugins/webserver-tomcat/src/main/java/org/bithon/agent/plugin/tomcat/interceptor/StandardHostValveInvoke.java
Some clients are using http 1.0. It's useful to add the version to tags to identify the client in one aspect.
=> Add http-version to trace tags

server/server-starter/src/main/resources/application.yml, server/sink/src/main/java/org/bithon/server/common/utils/MiscUtils.java, server/sink/src/main/java/org/bithon/server/common/utils/collection/IteratorableCollection.java, server/sink/src/main/java/org/bithon/server/tracing/TraceConfig.java, server/sink/src/main/java/org/bithon/server/tracing/mapping/TraceMappingFactory.java, server/sink/src/main/java/org/bithon/server/tracing/mapping/URIParameterExtractor.java, server/sink/src/main/java/org/bithon/server/tracing/sanitization/ISanitizer.java, server/sink/src/main/java/org/bithon/server/tracing/sanitization/SanitizerConfig.java, server/sink/src/main/java/org/bithon/server/tracing/sanitization/SanitizerFactory.java, server/sink/src/main/java/org/bithon/server/tracing/sanitization/UrlSanitizer.java, server/sink/src/main/java/org/bithon/server/tracing/sink/TraceMessageHandler.java, server/sink/src/main/java/org/bithon/server/tracing/sink/TraceSpan.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/SchemaStorage.java
After this, some sensitive information could be mask as demonstrated below
New configuration introduced by this PR:
```yaml
bithon:
tracing:
globalSanitizer:
type: uri
args:
sensitiveParameters:
- password
```
=> Support to sanitize sensitive information in trace span

server/sink/src/main/java/org/bithon/server/metric/storage/GroupByQuery.java, server/sink/src/main/java/org/bithon/server/metric/storage/Interval.java, server/sink/src/main/java/org/bithon/server/metric/storage/OrderBy.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/table/component.js, server/web-service/src/main/java/org/bithon/server/web/service/api/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/api/DataSourceService.java, server/web-service/src/main/java/org/bithon/server/web/service/api/GroupByQueryRequest.java, server/web-service/src/main/java/org/bithon/server/web/service/topo/api/TopoApi.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceService.java
1. Support OrderBy semantics on GroupBy query
2. Fix the value of interval in GroupBy query
For WebApp
1. Keeps the order state when table content is refreshed
3. Use the default formatter in detailed view if there's no formatter specified
=> Fix the value of interval in GroupBy query

agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/config/GatewayFilterConfigs.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/config/ResponseConfigs.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, doc/configuration/agent-plugin/spring-webflux.md, doc/configuration/configuration-agent.md
Supports the #321 
Allows to configure which headers in the responses should be logged to the `tags` of a span log. Currently WebFlux is supported to minimize the work. 
By doing this, the span logs can contain some users' customized headers in the span log so that these headers values can be searched in the span log from the metrics data.
=> Support to log HTTP Response headers

server/web-app/src/main/resources/static/js/component/searchbar/component.js
Fixes #359 
No changes on the server side although this would make the search less efficient.
The reason is how to determine the interval? Let's say if we search in [now - 1d, now] interval, what if there're some logs outside that range, for example in the range of [now -1d - xSecond, now - 1d]?
So, to simply the logic, the less efficient logic would give us correct result on the edge cases.
=> Remove time interval from search bar

server/sink/src/main/java/org/bithon/server/tracing/sink/TraceSpan.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcReader.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcWriter.java, server/web-app/src/main/java/org/bithon/server/webapp/ui/AppController.java, server/web-app/src/main/java/org/bithon/server/webapp/ui/DashboardController.java, server/web-app/src/main/java/org/bithon/server/webapp/ui/TraceController.java, server/web-app/src/main/resources/static/js/app-card-component.js, server/web-app/src/main/resources/static/js/component/app-selector/component.js, server/web-app/src/main/resources/static/js/component/dashboard/component.js, server/web-app/src/main/resources/static/js/component/sidebar/component.js, server/web-app/src/main/resources/static/js/page/trace/profiling-page.js, server/web-app/src/main/resources/static/js/utils/location.js, server/web-app/src/main/resources/templates/app/app-layout.html, server/web-app/src/main/resources/templates/app/dashboard.html, server/web-app/src/main/resources/templates/app/event.html, server/web-app/src/main/resources/templates/app/topo.html, server/web-app/src/main/resources/templates/trace/profiling.html
A profiling view helps to analyze the concurrent requests going to a specific instance.
Each rect on the chart is clickable to navigate to the full logs of that request
=> Add profiling page for tracing logs

agent/agent-sdk/src/main/java/org/bithon/agent/sdk/metric/aggregator/LongMax.java, agent/agent-sdk/src/main/java/org/bithon/agent/sdk/metric/aggregator/LongMin.java
Min/Max aggregator's initial value is LONG.MAX or LONG.MIN, if such aggregator has value provided, these two default values will be reported to the server side. This will cause inaccurate query results.
=> Add default value for min/max

server/collector/src/main/java/org/bithon/server/collector/sink/kafka/KafkaMetricSink.java, server/collector/src/main/java/org/bithon/server/collector/source/brpc/BrpcMetricCollector.java, server/collector/src/main/java/org/bithon/server/collector/source/http/MetricHttpCollector.java, server/server-starter/pom.xml, server/sink/src/main/java/org/bithon/server/kafka/KafkaMetricConsumer.java, server/sink/src/main/java/org/bithon/server/sink/event/EventsMessageHandler.java, server/sink/src/main/java/org/bithon/server/sink/metrics/AbstractMetricMessageHandler.java, server/sink/src/main/java/org/bithon/server/sink/metrics/IMetricMessageSink.java, server/sink/src/main/java/org/bithon/server/sink/metrics/LocalMetricSink.java, server/sink/src/main/java/org/bithon/server/sink/metrics/LocalSchemaMetricSink.java, server/sink/src/main/java/org/bithon/server/sink/metrics/SchemaMetricMessage.java, server/sink/src/main/java/org/bithon/server/sink/tracing/TraceMessageHandler.java, server/sink/src/main/java/org/bithon/server/sink/tracing/metrics/MetricOverSpanInputSource.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/event/EventJdbcStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcWriter.java
1. This is a revert and is not the best solution to support hundreds and thousands different types of metrics processing. For large amount of different metrics, should be one queue per metric and a shared executor to schedule the processing.
2. Update calling of batch interface of jOOQ to simplify the SQL
3. Add actuator
=> Use thread executor per metric

agent/agent-plugins/mysql-5.x-6.x/pom.xml, agent/agent-plugins/mysql-8.x/pom.xml
To eliminate warnings reported by dependent bot. Although agent only declares these dependencies as 'provided'
=> bump mysql-connector-java

server/storage/src/main/java/org/bithon/server/storage/datasource/spec/CountMetricSpec.java, server/storage/src/main/java/org/bithon/server/storage/datasource/spec/gauge/GaugeMetricSpec.java, server/storage/src/main/java/org/bithon/server/storage/datasource/spec/max/MaxMetricSpec.java, server/storage/src/main/java/org/bithon/server/storage/datasource/spec/min/MinMetricSpec.java, server/storage/src/main/java/org/bithon/server/storage/datasource/spec/sum/SumMetricSpec.java
For `IMetricSpec`, `name` property should always used when querying instead of using `field`
=> Fix query generation bug

agent/agent-distribution/distribution.xml, agent/agent-distribution/pom.xml, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/GrpcPlugin.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/AbstractAsyncStub$NewStub.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/AbstractFutureStub$NewStub.java, agent/agent-plugins/grpc/src/main/java/org/bithon/agent/plugin/grpc/client/interceptor/AbstractGrpcStubInterceptor.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/interceptor/ForkJoinPool$Ctor.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/interceptor/ThreadPoolExecutor$Ctor.java, agent/agent-plugins/jdk-thread/src/main/java/org/bithon/agent/plugin/thread/utils/ThreadPoolUtils.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/HttpChannel$Handle.java, agent/agent-plugins/webserver-tomcat/src/main/java/org/bithon/agent/plugin/tomcat/interceptor/StandardHostValveInvoke.java, agent/agent-plugins/webserver-undertow/src/main/java/org/bithon/agent/plugin/undertow/interceptor/HttpServerExchangeDispatch.java, component/component-commons/src/main/java/org/bithon/component/commons/tracing/Tags.java
1.Many business libs does not specify ThreadFactory when creating a thread pool. In such case, `Executors.defaultThreadFactory()` is used internally. This default thread factory initializes a unique name as `pool-{a number}-`. This name is meaningless for observability. We improve it by using the class name of caller which creates the thread pool object.
2. Support remote.address
3. Support async/future stub
=> Improve thread pool name

server/collector/src/main/java/org/bithon/server/collector/sink/kafka/FixedSizeBuffer.java, server/collector/src/main/java/org/bithon/server/collector/sink/kafka/KafkaMessage.java, server/collector/src/main/java/org/bithon/server/collector/sink/kafka/KafkaMetricSink.java, server/collector/src/main/java/org/bithon/server/collector/sink/kafka/KafkaTraceSink.java, server/collector/src/main/java/org/bithon/server/collector/source/brpc/BrpcCollectorStarter.java, server/sink/src/main/java/org/bithon/server/sink/tracing/ITraceMessageSink.java, server/sink/src/main/java/org/bithon/server/sink/tracing/TraceBatchWriter.java, server/sink/src/main/java/org/bithon/server/sink/tracing/mapping/TraceMappingFactory.java, server/sink/src/test/java/org/bithon/server/sink/tracing/mapping/URIParameterExtractorTest.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/TraceStorage.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcReader.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/TraceJdbcStorage.java, server/storage/src/main/java/org/bithon/server/storage/tracing/ITraceReader.java, server/storage/src/main/java/org/bithon/server/storage/tracing/mapping/TraceIdMapping.java, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceService.java
1. Split messages for metrics when sending to kafka
2. Use timestamp of mapped id to search tracing in order to gain better query performance
3. Save tx id in mapped id so that if an id is not found no further search will be performed
=> Sink Improvement

README.md, agent/agent-controller/src/main/java/org/bithon/agent/controller/AgentControllerService.java, agent/agent-controller/src/main/java/org/bithon/agent/controller/IAgentController.java, agent/agent-controller/src/main/java/org/bithon/agent/controller/config/DynamicConfigurationManager.java, agent/agent-core/src/main/java/org/bithon/agent/configuration/Configuration.java, agent/agent-core/src/main/java/org/bithon/agent/starter/AgentStarter.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcAgentController.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcEventMessageChannel.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcMetricMessageChannel.java, agent/agent-dispatcher-brpc/src/main/java/org/bithon/agent/dispatcher/brpc/BrpcTraceMessageChannel.java, agent/agent-distribution/resources/agent.yml, agent/agent-observability/src/main/java/org/bithon/agent/observability/context/AppConfiguration.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/context/AppInstance.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/Tracer.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/utils/NetworkUtils.java, docker/README.md, server/collector/src/main/java/org/bithon/server/collector/config/AgentConfigurationService.java, server/collector/src/main/java/org/bithon/server/collector/config/BrpcSettingFetcher.java
Remove `bithon.application.env` from document, no need to configure it. Keep it in code for compatibility
=> Simplifies configuration

component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcClient.java, component/component-brpc/src/main/java/org/bithon/component/brpc/channel/BrpcServer.java, component/component-brpc/src/main/java/org/bithon/component/brpc/invocation/InvocationManager.java, component/component-brpc/src/test/java/org/bithon/component/brpc/BrpcRpcTest.java, server/collector/src/main/java/org/bithon/server/collector/source/brpc/BrpcCollectorStarter.java
A lots of sessions are observed by executing diagnosis SQL on an instance what is deployed in remote DC region. Might be caused by broken connections. So server side idle processing is necessary.
=> Add server side idle support to brpc server

agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/TraceContextListener.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/impl/TracingContext.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/impl/TracingSpan.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/AroundGatewayFilter$Filter.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientFinalizer$ResponseConnection.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/HttpClientFinalizer$Send.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java
Fixes #588
This is because when the exception is raised, 'doFinally' hooked by the filter is triggered after the web-server's 'finish'
=> Fix unmatched 'finish' call

agent/agent-controller/src/main/java/org/bithon/agent/controller/cmd/InstrumentationCommand.java, agent/agent-instrumentation/src/main/java/org/bithon/agent/instrumentation/aop/interceptor/InterceptorSupplier.java, agent/agent-plugins/logging-log4j2/src/main/java/org/bithon/agent/plugin/log4j2/Log4j2Plugin.java, agent/agent-plugins/logging-log4j2/src/main/java/org/bithon/agent/plugin/log4j2/interceptor/Logger$LogMessage.java, component/agent-rpc-brpc/src/main/java/org/bithon/agent/rpc/brpc/cmd/IInstrumentationCommand.java, component/component-commons/src/main/java/org/bithon/component/commons/logging/LoggerFactory.java
This also prevents periodically instantiate the interceptor once it fails to instantiate. 
One case is that the Kafka plugin targets the 2.5 or higher, some lower kafka clients miss some classes referenced by the 2.5 which are indirectly referenced by the interceptors.
=> Prevent NPE from InstrumentationCommand in case interceptor fails to load

agent/agent-distribution/resources/agent.yml, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/config/TraceConfig.java, agent/agent-observability/src/main/java/org/bithon/agent/observability/tracing/context/TraceMode.java, agent/agent-plugins/spring-webflux/src/main/java/org/bithon/agent/plugin/spring/webflux/interceptor/ReactorHttpHandlerAdapter$Apply.java, agent/agent-plugins/webserver-jetty/src/main/java/org/bithon/agent/plugin/jetty/interceptor/HttpChannel$Handle.java, agent/agent-plugins/webserver-tomcat/src/main/java/org/bithon/agent/plugin/tomcat/interceptor/StandardHostValve$Invoke.java, agent/agent-plugins/webserver-undertow/src/main/java/org/bithon/agent/plugin/undertow/interceptor/HttpServerExchangeDispatch.java
Some applications do not trace all requests. For these un-traced requests, a trace id is still generated for logging purpose. In such case, the trace id, trace mode in the response is still meaningful.
=> Add trace mode to response

server/collector/src/main/java/org/bithon/server/collector/http/TraceHttpCollector.java, server/collector/src/main/java/org/bithon/server/collector/http/TraceHttpCollectorConfig.java, server/pipeline/src/main/java/org/bithon/server/pipeline/PipelineAutoConfiguration.java, server/pipeline/src/main/java/org/bithon/server/pipeline/common/FixedSizeBuffer.java, server/pipeline/src/main/java/org/bithon/server/pipeline/event/exporter/KafkaEventExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/event/exporter/ToEventStorageExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/event/receiver/KafkaEventReceiver.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/exporter/ToKafkaExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/exporter/ToMetricStorageExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/input/MetricInputSourceManager.java, server/pipeline/src/main/java/org/bithon/server/pipeline/metrics/input/MetricInputSourceManagerStub.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/exporter/ToKafkaExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/exporter/ToTraceStorageExporter.java, server/pipeline/src/main/java/org/bithon/server/pipeline/tracing/receiver/KafkaTraceReceiver.java, server/server-starter/src/main/resources/application-pipeline-to-kafka.yml
Fixes #724 
Fixes #646
1. change the format of kafka message from json array to json each row
2. limit the size of spans deserialized
3. limit the size of spans that are wrapped into one kafka message
This leads to increasing of kafka messages but reduced the overhead at the receiver side
=> Improve the memory usage

component/component-commons/src/main/java/org/bithon/component/commons/expression/IDataType.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/MapAccessExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/optimzer/ExpressionOptimizer.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/serialization/ExpressionSerializer.java, server/server-starter/src/main/resources/application-storage-h2.yml, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/optimizer/HasTokenFunctionOptimizer.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/trace/TraceStorage.java, server/storage-jdbc-h2/src/main/java/org/bithon/server/storage/jdbc/h2/H2SqlDialect.java, server/storage-jdbc-mysql/src/main/java/org/bithon/server/storage/jdbc/mysql/MySQLSqlDialect.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/dialect/MapAccessExpressionTransformer.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/tracing/reader/TraceJdbcReader.java, server/storage/src/main/java/org/bithon/server/storage/common/expression/ExpressionASTBuilder.java, server/storage/src/main/java/org/bithon/server/storage/common/expression/IdentifierProvider.java, server/storage/src/main/java/org/bithon/server/storage/datasource/column/ObjectColumn.java, server/storage/src/main/java/org/bithon/server/storage/tracing/ITraceReader.java, server/storage/src/main/java/org/bithon/server/storage/tracing/TraceTableSchema.java, server/web-app/src/main/resources/dashboard/http-outgoing-metrics.json, server/web-app/src/main/resources/dashboard/kafka-consumer-metrics.json, server/web-app/src/main/resources/dashboard/kafka-producer-metrics.json, server/web-app/src/main/resources/dashboard/redis-metrics.json, server/web-app/src/main/resources/static/js/page/trace/page.js, server/web-service/src/main/java/org/bithon/server/web/service/tracing/service/TraceService.java
Fixes #770
1. use map access expression for 'tags'
2. validate map access expression
3. uses new expression syntax at the FE side
This also introduces incompatibility for old schema that actually has Map datatype used in the underlying storage. These must be updated to use the new IDataType.OBJECT
=> Use map access syntax for tags search

docker/Dockerfile-server
heap can utilize up to 90% of max heap 
jdk21
while jdk8 utilizes up to 75% by default of max heap configured
=> Change default JDK in docker image to JDK 21

README.md, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/KafkaPlugin.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/KafkaPluginContext.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/admin/interceptor/AdminClient$Create.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/admin/interceptor/KafkaAdminClient$All.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/FetchMetricsAggregator$Ctor.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/FetchMetricsAggregator$Record.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/FetchResponseMetricAggregator$Ctor.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/FetchResponseMetricAggregator$Record.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/KafkaConsumer$Ctor.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/KafkaConsumer$Poll.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/ListenerConsumer$Ctor.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/consumer/interceptor/ListenerConsumer$PollAndInvoke.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/network/interceptor/NetworkClient$CompleteResponses.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/producer/interceptor/KafkaProducer$Ctor.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/producer/interceptor/KafkaProducer$DoSend.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/producer/interceptor/SenderMetrics$RecordErrors.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/producer/interceptor/SenderMetrics$RecordRetries.java, agent/agent-plugins/apache-kafka/src/main/java/org/bithon/agent/plugin/apache/kafka/producer/interceptor/SenderMetrics$UpdateProduceRequestMetrics.java
3.x refactors the KafkaConsumer into LegacyKafkaConsumer and async mode consumer. In this pr, only the legacy mode is supported.
And the metrics of fetch is also improved by using the batch interface to improve the performance
=> Support kafka consumer 3.7

server/alerting/README.md, server/alerting/common/src/main/java/org/bithon/server/alerting/common/model/AlertRule.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/evaluator/AlertEvaluator.java, server/alerting/evaluator/src/main/java/org/bithon/server/alerting/evaluator/storage/redis/AlertStateRedisStorage.java, server/alerting/manager/alert-command-api.http, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/AlertChannelApi.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/AlertQueryApi.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/api/parameter/CreateAlertRuleRequest.java, server/alerting/manager/src/main/java/org/bithon/server/alerting/manager/biz/AlertCommandService.java, server/alerting/notification/src/main/java/org/bithon/server/alerting/notification/channel/http/HttpNotificationChannel.java, server/alerting/notification/src/main/java/org/bithon/server/alerting/notification/image/AlertImageRenderService.java, server/server-commons/src/main/java/org/bithon/server/commons/utils/HumanReadableDurationValidator.java, server/storage/src/main/java/org/bithon/server/storage/alerting/pojo/NotificationProps.java, server/web-app/src/main/resources/static/js/alert/alert-edit-component.js
so that it's able to control which expressions can be rendered.
**Background:**
Some alert rule has composite expressions, some of which are just pre-conditions. There's no need to render these expressions in IMAGE.
=> Update notification props to control rendered expressions

server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/TableCreator.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/exception/RetryableExceptions.java
#789 
```text
┌─partition─┬─partCount─┬─rowsCount─┬────diskSize─┬─onDiskSize─┬─compressedSize─┬─uncompressedSize─┬─compressRatio(%)─┐
92. │ 20241213  │        14 │ 292964166 │ 17221545315 │ 16.04 GiB  │ 16.02 GiB      │ 57.83 GiB        │               28 │
94. │ 20241215  │        14 │ 292331053 │ 12466005304 │ 11.61 GiB  │ 11.59 GiB      │ 57.69 GiB        │               20 │
```
By enforcing codec for dimensions, storage size of `http-incoming-metrics` reduced by 30% as illustrated above.
=> reduce storage size

component/component-commons/src/main/java/org/bithon/component/commons/expression/ArithmeticExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/IDataType.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/LiteralExpression.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/builtin/AggregateFunction.java, component/component-commons/src/main/java/org/bithon/component/commons/expression/function/builtin/TimeFunction.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/QueryExpressionBuilder.java, server/storage-jdbc/src/test/java/org/bithon/server/storage/jdbc/metric/QueryExpressionBuilderTest.java, server/storage/src/main/java/org/bithon/server/storage/datasource/DefaultSchema.java, server/storage/src/main/java/org/bithon/server/storage/datasource/column/DateTimeColumn.java, server/storage/src/main/java/org/bithon/server/storage/datasource/column/ExpressionColumn.java, server/storage/src/main/java/org/bithon/server/storage/datasource/column/LongColumn.java, server/storage/src/main/java/org/bithon/server/storage/datasource/column/ObjectColumn.java, server/storage/src/main/java/org/bithon/server/storage/datasource/column/StringColumn.java, server/storage/src/main/java/org/bithon/server/storage/datasource/column/aggregatable/IAggregatableColumn.java, server/storage/src/main/java/org/bithon/server/storage/datasource/query/ast/Expression.java, server/storage/src/main/java/org/bithon/server/storage/datasource/query/ast/Selector.java, server/storage/src/main/java/org/bithon/server/storage/datasource/query/ast/SelectorList.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/QueryResponse.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/DataSourceApi.java, server/web-service/src/main/java/org/bithon/server/web/service/datasource/api/impl/QueryConverter.java
so that FE can initialize default formatters by the data type. for example, for date time column, the date time formatter will be applied
=> return data type in meta

server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/ClickHouseSqlDialect.java, server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/optimizer/ClickHouseExpressionOptimizer.java, server/storage-jdbc-h2/src/main/java/org/bithon/server/storage/jdbc/h2/H2SqlDialect.java, server/storage-jdbc-mysql/src/main/java/org/bithon/server/storage/jdbc/mysql/MySQLSqlDialect.java, server/storage-jdbc-postgresql/src/main/java/org/bithon/server/storage/jdbc/postgresql/PostgresqlDialect.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/dialect/Expression2Sql.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/dialect/ISqlDialect.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/statement/Expression2SqlSerializer.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/statement/SelectStatementBuilder.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/statement/SelectStatementPipeline.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/common/statement/SqlGenerator.java, server/storage-jdbc/src/main/java/org/bithon/server/storage/jdbc/metric/MetricJdbcReader.java, server/storage-jdbc/src/test/java/org/bithon/server/storage/jdbc/common/statement/SelectStatementBuilderTest.java, server/storage/src/main/java/org/bithon/server/storage/datasource/query/ast/IASTNodeVisitor.java, server/storage/src/main/java/org/bithon/server/storage/datasource/query/ast/SelectStatement.java
Separated from #1000 and apply some refactoring on underlying sql objects.
Background:
at the api layer, we can accept expression like: sum(a), it needs to be turned into sumMerge(a) if a is a AggregateFunction type. This is done if the sum(a) is passed by the aggregator and field property in the QueryField, but missed if it's pass by the expression property.
=> Apply optimization for function expressions

server/storage-jdbc-clickhouse/src/main/java/org/bithon/server/storage/jdbc/clickhouse/common/optimizer/ClickHouseExpressionOptimizer.java, server/storage-jdbc-clickhouse/src/test/java/org/bithon/server/storage/jdbc/clickhouse/common/optimizer/ClickHouseExpressionOptimizerTest.java
When expression `count()` is given, index out of range exception is thrown. introduced by #1002
=> Fix out of range exception
